# Generates Grassmann/Composite/Kinds.lean: one-line wrappers of the derived composite functions
# for the element kinds that have no specialised form (see the module doc it writes).
import re, glob
import os
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..') + '/'
defs = {}
for f in sorted(glob.glob(root + 'Grassmann/Composite/*.lean')):
    if f.endswith('Kinds.lean'):
        continue
    ns = []
    for line in open(f):
        m = re.match(r'namespace (\S+)', line)
        if m:
            ns.append(m.group(1)); continue
        m = re.match(r'end (\S+)', line)
        if m and ns and ns[-1] == m.group(1):
            ns.pop(); continue
        m = re.search(r'\bdef (\S+)', line)
        if m:
            name = m.group(1)
            if '.' in name:
                k, n = name.rsplit('.', 1)
            else:
                k = ns[-1] if ns else '_'
                n = name
            defs.setdefault(n, set()).add(k)

refs = {
 'tanh': ('sinh(t)/cosh(t)', 'AT:419'), 'cot': ('cos(t)/sin(t)', 'AT:410'), 'sec': ('inv(cos(t))', 'AT:411'),
 'csc': ('inv(sin(t))', 'AT:412'), 'coth': ('cosh(t)/sinh(t)', 'AT:420'), 'sech': ('inv(cosh(t))', 'AT:415'),
 'csch': ('inv(sinh(t))', 'AT:416'), 'asinh': ('log(t + sqrt(1 + t⟑t))', 'AT:421'),
 'acosh': ('log(t + sqrt(t⟑t - 1))', 'AT:422'), 'atanh': ('(log(1+t) - log(1-t))/2', 'AT:423'),
 'acoth': ('(log(t+1) - log(t-1))/2', 'AT:424'), 'asin': ('(-I) ⟑ log(I⟑t + sqrt(1 - t⟑t))', 'AT:425'),
 'acos': ('(-I) ⟑ log(t + I⟑sqrt(1 - t⟑t))', 'AT:426'), 'atan': ('((-I)/2) ⟑ (log(1 + I⟑t) - log(1 - I⟑t))', 'AT:427'),
 'acot': ('((-I)/2) ⟑ (log(t - I) - log(t + I))', 'AT:428'), 'asec': ('acos(inv(t))', 'AT:413'),
 'acsc': ('asin(inv(t))', 'AT:414'), 'asech': ('acosh(inv(t))', 'AT:417'), 'acsch': ('asinh(inv(t))', 'AT:418'),
 'sinc': ('sinc(t)', 'AT:429'), 'cosc': ('cosc(t)', 'AT:430'), 'sqrt': ('sqrt(t)', 'C:436-451'),
 'cbrt': ('cbrt(t)', 'C:436-451'), 'exp2': ('exp(log(2)·t)', 'AT:384'), 'exp10': ('exp(log(10)·t)', 'AT:384'),
 'log2': ('log2(ℯ)·log(t)', 'AT:383'), 'log10': ('log10(ℯ)·log(t)', 'AT:383'),
}
fns = ['tanh', 'cot', 'sec', 'csc', 'coth', 'sech', 'csch', 'asin', 'acos', 'atan', 'acot', 'asec',
       'acsc', 'asinh', 'acosh', 'atanh', 'acoth', 'asech', 'acsch', 'sinc', 'cosc', 'exp2', 'exp10',
       'log2', 'log10']
# kind: (namespace, extra variables, parameter type, doc name)
kinds = [
 ('Single', '{G : Nat}', 'Single V G Float', 'term'),
 ('Chain', '{G : Nat}', 'Chain V G Float', 'chain'),
 ('Couple', '', 'Couple V Float', 'couple'),
 ('PseudoCouple', '', 'PseudoCouple V Float', 'pseudo-couple'),
 ('Half', '', 'Half V false Float', 'spinor'),
 ('CoSpinor', '', 'CoSpinor V Float', 'co-spinor'),
]
out = []
out.append('''/-
The derived composite functions (`tanh`, `cot`, `sec`, `csc`, `coth`, `sech`, `csch`, the inverse
trigonometric and hyperbolic functions, `sinc`, `cosc`, `exp2`, `exp10`, `log2`, `log10`, and
`sqrt`/`cbrt` of a pseudo-couple) on every element kind that has no specialised form: AbstractTensors'
generic definitions (`AT:383-430`), evaluated on the element's multivector (Julia evaluates them on
the element, whose kinds combine to the same values; the result here is the `Multivector`).

GENERATED by `oracle/forms/gen_kinds.py` (`uv run oracle/forms/gen_kinds.py`), which lists the
(kind, function) pairs no other `Grassmann.Composite` module defines. Julia throws for several of
them (`asin`/`asinh` of a chain overflow the stack, `cot` of a couple and the phasor functions
hit an `UndefVarError`, `acos` of a spinor an `ErrorException`); here they are the functions'
values.
-/
import Grassmann.Composite.Phasor

namespace Grassmann

open DirectSum StaticVectors AbstractTensors Composite

variable {V : TensorBundle} [Kernels V]
''')
count = 0
for (ns, extra, ty, doc) in kinds:
    missing = [f for f in fns if ns not in defs.get(f, set()) and not (ns == 'PseudoCouple' and False)]
    if ns != 'PseudoCouple':
        missing = [f for f in missing if f not in ('sqrt', 'cbrt')]
    else:
        missing = [f for f in ['sqrt', 'cbrt'] if ns not in defs.get(f, set())] + missing
    if not missing:
        continue
    out.append(f'namespace {ns}\n')
    if extra:
        out.append(f'variable {extra}\n')
    for f in missing:
        body, ref = refs[f]
        out.append(f'/-- AbstractTensors `{f}(t)` (`{body}`, `{ref}`) of a {doc}, on its multivector. -/')
        out.append(f'@[specialize V] def {f} (t : {ty}) : Multivector V Float := Multivector.{f} (toMultivector t)\n')
        count += 1
    out.append(f'end {ns}\n')

# phasors: through the couple they complexify to
out.append('namespace Phasor\n')
for f in ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'cot', 'sec', 'csc', 'coth', 'sech', 'csch',
          'asin', 'acos', 'atan', 'acot', 'asinh', 'acosh', 'atanh', 'acoth']:
    if 'Phasor' in defs.get(f, set()):
        continue
    out.append(f'/-- Julia `{f}(z::Phasor)`: `{f}(complexify(z))` (a phasor is a couple in polar form). -/')
    out.append(f'@[specialize V] def {f} (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.{f} z.complexify)\n')
    count += 1
out.append('end Phasor\n')
out.append('end Grassmann\n')
open(root + 'Grassmann/Composite/Kinds.lean', 'w').write('\n'.join(out))
print('defs', count)
