import Grassmann.Forms

/-!
# Generator of `Grassmann/Forms/Unrolled.lean`

    lake env lean --run oracle/forms/GenUnrolled.lean > Grassmann/Forms/Unrolled.lean

Runs the generic determinant-family algorithms of `Grassmann.Forms.Compound` (`det`,
the Cramer `inv`, `adjugate`, `solve`: DirectSum's wedge plans, prefix/suffix Cramer
symbols, complements) on a **symbolic** coefficient type that records every `+`, `-`, `*`,
`/`, negation and constant, and prints the recorded computation as straight-line Lean
code generic over `[Coeff α]`. Because the generated functions perform exactly the
operations of the generic algorithm in exactly its order, they are bit-identical to it at
`Float` (signed zeros included), and so to Julia; `Tests/Forms/Unrolled.lean` checks this
on random operators.

Shared subterms (the prefix and suffix wedges) are the same objects in the recorded
computation and are emitted once (memoized by pointer).
-/

namespace GenUnrolled

open Grassmann DirectSum StaticVectors AbstractTensors Grassmann.Forms

/-- A symbolic coefficient: an input slot or an operation of the generic algorithm. -/
inductive Sym where
  | zero
  | one
  | int (k : Int)
  | raw (k : Nat)
  | vec (k : Nat)
  | add (a b : Sym)
  | sub (a b : Sym)
  | mul (a b : Sym)
  | div (a b : Sym)
  | neg (a : Sym)
  deriving Inhabited

instance : Coeff Sym where
  add := .add
  sub := .sub
  mul := .mul
  neg := .neg
  zero := .zero
  one := .one
  ofInt k := if k == 0 then .zero else if k == 1 then .one else .int k
  ofRat r := .int r.num
  isZero x := match x with | .zero => true | _ => false

instance : Div Sym := ⟨.div⟩

/-- Emission state: the memo (object address → name), the lines, a counter. -/
structure St where
  memo : Std.HashMap USize String := {}
  lines : Array String := #[]
  n : Nat := 0

/-- The expression of a node, emitting `let`s for compound nodes (memoized by address). -/
unsafe def emit (s : Sym) : StateM St String := do
  match s with
  | .zero => return "Coeff.zero"
  | .one => return "Coeff.one"
  | .int k => return s!"(Coeff.ofInt ({k}))"
  | .raw k => return s!"a{k}"
  | .vec k => return s!"b{k}"
  | _ =>
    let key := ptrAddrUnsafe s
    if let some nm := (← get).memo[key]? then return nm
    let rhs : String ← match s with
      | .add a b => do let x ← emit a; let y ← emit b; pure s!"{x} + {y}"
      | .sub a b => do let x ← emit a; let y ← emit b; pure s!"{x} - {y}"
      | .mul a b => do let x ← emit a; let y ← emit b; pure s!"{x} * {y}"
      | .div a b => do let x ← emit a; let y ← emit b; pure s!"{x} / {y}"
      | .neg a => do let x ← emit a; pure s!"-{x}"
      | _ => pure "Coeff.zero"
    let st ← get
    let nm := s!"t{st.n}"
    set { st with memo := st.memo.insert key nm, lines := st.lines.push s!"  let {nm} := {rhs}", n := st.n + 1 }
    return nm

/-- The symbolic `n × n` operator (entry `(i, j)` is raw slot `j·n + i`, column-major). -/
def symOp (n : Nat) : Simplex (E n) (E n) Sym := TensorOperator.ofFn fun i j => .raw (j.1 * n + i.1)

/-- The symbolic vector of `ℝⁿ`. -/
def symVec (n : Nat) : Chain (E n) 1 Sym := ⟨Values.ofFn fun i => .vec i.1⟩

/-- The input bindings of the raw operator (and vector) slots. -/
def inputs (n : Nat) (withVec : Bool) : Array String :=
  ((Array.range (n * n)).map fun k => s!"  let a{k} := Mat.rd raw {k}") ++
    (if withVec then (Array.range n).map fun k => s!"  let b{k} := Mat.rd vv {k}" else #[])

/-- `Packed.push (… (Packed.push (Packed.mkEmpty k) x₀) …) xₖ₋₁`. -/
def pushes (xs : Array String) : String :=
  xs.foldl (fun acc x => s!"Packed.push ({acc}) {x}") s!"Packed.mkEmpty {xs.size}"

/-- A function returning the listed symbolic outputs as raw storage (or a scalar). -/
unsafe def defn (name doc sig : String) (n : Nat) (withVec : Bool) (outs : Array Sym) (scalar : Bool) :
    String :=
  let (res, st) := (outs.mapM emit).run {}
  let body := if scalar then res[0]! else pushes res
  let lines := inputs n withVec ++ st.lines ++ #[s!"  {body}"]
  s!"/-- {doc} -/\n@[specialize] def {name} {sig} :=\n" ++ "\n".intercalate lines.toList ++ "\n"

/-- The generated module. -/
unsafe def main : IO Unit := do
  IO.println "/-
Straight-line forms of the determinant family of `n × n` grade-1 operators, `n = 2 … 6`:
`det`, the Cramer `inv`, the `adjugate` and the Cramer `solve` (Julia `value(T) \\ v`).

GENERATED by `oracle/forms/GenUnrolled.lean` (`lake env lean --run oracle/forms/GenUnrolled.lean
> Grassmann/Forms/Unrolled.lean`): each function is the generic algorithm of
`Grassmann.Forms.Compound` (DirectSum's wedge plans, Julia's Cramer symbols and complements)
run on symbolic coefficients and printed operation by operation, so it is bit-identical to the
generic algorithm (and to Julia) at `Float`. Inputs are column-major raw storage (`(i, j)` at
`j·n + i`); matrix results are column-major. Do not edit by hand.
-/
import Grassmann.Forms.Mat

namespace Grassmann.Forms.Unrolled

open StaticVectors AbstractTensors Grassmann.Forms

variable {α : Type} [Coeff α]
"
  for n in [5, 6] do
    let T := symOp n
    IO.println (defn s!"det{n}" s!"`det` of a `{n} × {n}` operator (the wedge of its columns)."
      "(raw : Packed.Arr α) : α" n false #[T.detGeneric] true)
  for n in [5, 6] do
    let T := symOp n
    IO.println (defn s!"inv{n}" s!"The Cramer inverse of a `{n} × {n}` operator (`invSquare`), column-major."
      "[Div α] (raw : Packed.Arr α) : Packed.Arr α" n false T.invSquareGeneric.mat.v.data false)
  for n in [2, 3, 4, 5, 6] do
    let T := symOp n
    IO.println (defn s!"adjugate{n}" s!"The adjugate of a `{n} × {n}` operator (Julia's Cramer rows), column-major."
      "(raw : Packed.Arr α) : Packed.Arr α" n false T.adjugateGeneric.mat.v.data false)
  for n in [2, 3, 4, 5, 6] do
    let T := symOp n
    IO.println (defn s!"solve{n}" s!"The Cramer solve (Julia `value(T) \\ v`) of a `{n} × {n}` operator."
      "[Div α] (raw vv : Packed.Arr α) : Packed.Arr α" n true (T.solveGeneric (symVec n)).v.data false)
  IO.println "end Grassmann.Forms.Unrolled"

end GenUnrolled

unsafe def main : IO Unit := GenUnrolled.main
