import Grassmann.Forms

/-!
# Generator of `Grassmann/Forms/Unrolled.lean` and `Grassmann/Forms/UnrolledMat.lean`

    lake env lean --run oracle/forms/GenUnrolled.lean > Grassmann/Forms/Unrolled.lean
    lake env lean --run oracle/forms/GenUnrolled.lean mat > Grassmann/Forms/UnrolledMat.lean

Runs generic algorithms of `Grassmann.Forms` on a **symbolic** coefficient type that records
every `+`, `-`, `*`, `/`, negation and constant, and prints the recorded computation as
straight-line Lean code generic over `[Coeff α]`:

* `Unrolled`: the determinant family of `Grassmann.Forms.Compound` (`detGeneric`, the
  Cramer `invSquareGeneric`, `adjugateGeneric`, `solveGeneric`: DirectSum's wedge plans,
  prefix/suffix Cramer symbols, complements) and `characteristicGeneric`;
* `UnrolledMat`: the matrix-vector and matrix-matrix products of `Grassmann.Forms.Mat` for
  `5 × 5` and `6 × 6` (the strided dots, Julia's order).

Because the generated functions perform exactly the operations of the generic algorithms in
exactly their order, they are bit-identical to them at `Float` (signed zeros included), and
so to Julia; `Tests/Forms/Unrolled.lean` checks this on random operators. Shared subterms (the
prefix and suffix wedges) are the same objects in the recorded computation and are emitted
once (memoized by pointer).
-/

namespace GenUnrolled

open Grassmann DirectSum StaticVectors AbstractTensors Grassmann.Forms

/-- A symbolic coefficient: an input slot or an operation of the generic algorithm. -/
inductive Sym where
  | zero
  | one
  | int (k : Int)
  | raw (k : Nat)
  | vec (k : Nat)
  | add (a b : Sym)
  | sub (a b : Sym)
  | mul (a b : Sym)
  | div (a b : Sym)
  | neg (a : Sym)
  deriving Inhabited

instance : Coeff Sym where
  add := .add
  sub := .sub
  mul := .mul
  neg := .neg
  zero := .zero
  one := .one
  ofInt k := if k == 0 then .zero else if k == 1 then .one else .int k
  ofRat r := .int r.num
  isZero x := match x with | .zero => true | _ => false

instance : Div Sym := ⟨.div⟩

/-- Emission state: the memo (object address → name), the lines, a counter. -/
structure St where
  memo : Std.HashMap USize String := {}
  lines : Array String := #[]
  n : Nat := 0

/-- The expression of a node, emitting `let`s for compound nodes (memoized by address). -/
unsafe def emit (s : Sym) : StateM St String := do
  match s with
  | .zero => return "Coeff.zero"
  | .one => return "Coeff.one"
  | .int k => return s!"(Coeff.ofInt ({k}))"
  | .raw k => return s!"a{k}"
  | .vec k => return s!"b{k}"
  | _ =>
    let key := ptrAddrUnsafe s
    if let some nm := (← get).memo[key]? then return nm
    let rhs : String ← match s with
      | .add a b => do let x ← emit a; let y ← emit b; pure s!"{x} + {y}"
      | .sub a b => do let x ← emit a; let y ← emit b; pure s!"{x} - {y}"
      | .mul a b => do let x ← emit a; let y ← emit b; pure s!"{x} * {y}"
      | .div a b => do let x ← emit a; let y ← emit b; pure s!"{x} / {y}"
      | .neg a => do let x ← emit a; pure s!"-{x}"
      | _ => pure "Coeff.zero"
    let st ← get
    let nm := s!"t{st.n}"
    set { st with memo := st.memo.insert key nm, lines := st.lines.push s!"  let {nm} := {rhs}", n := st.n + 1 }
    return nm

/-- The symbolic `n × n` operator (entry `(i, j)` is raw slot `j·n + i`, column-major). -/
def symOp (n : Nat) : Simplex (E n) (E n) Sym := TensorOperator.ofFn fun i j => .raw (j.1 * n + i.1)

/-- A second symbolic `n × n` operator (the `vec` slots). -/
def symOp2 (n : Nat) : Simplex (E n) (E n) Sym := TensorOperator.ofFn fun i j => .vec (j.1 * n + i.1)

/-- The symbolic vector of `ℝⁿ`. -/
def symVec (n : Nat) : Chain (E n) 1 Sym := ⟨Values.ofFn fun i => .vec i.1⟩

/-- The input bindings: `na` slots of `raw`, `nb` slots of `vv`, read with `rd`. -/
def inputs (rd : String) (na nb : Nat) : Array String :=
  ((Array.range na).map fun k => s!"  let a{k} := {rd} raw {k}") ++
    (Array.range nb).map fun k => s!"  let b{k} := {rd} vv {k}"

/-- `Packed.push (… (Packed.push (Packed.mkEmpty k) x₀) …) xₖ₋₁`. -/
def pushes (xs : Array String) : String :=
  xs.foldl (fun acc x => s!"Packed.push ({acc}) {x}") s!"Packed.mkEmpty {xs.size}"

/-- A function returning the listed symbolic outputs as raw storage (or a scalar). -/
unsafe def defn (rd name doc sig : String) (na nb : Nat) (outs : Array Sym) (scalar : Bool) : String :=
  let (res, st) := (outs.mapM emit).run {}
  let body := if scalar then res[0]! else pushes res
  let lines := inputs rd na nb ++ st.lines ++ #[s!"  {body}"]
  s!"/-- {doc} -/\n@[specialize] def {name} {sig} :=\n" ++ "\n".intercalate lines.toList ++ "\n"

/-- The header of a generated module. -/
def header (what imp ns cmd : String) : String :=
  s!"/-
{what}

GENERATED by `oracle/forms/GenUnrolled.lean` (`lake env lean --run oracle/forms/GenUnrolled.lean{cmd}`):
each function is a generic algorithm of `Grassmann.Forms` run on symbolic coefficients and
printed operation by operation, so it is bit-identical to the generic algorithm (and to Julia)
at `Float`. Inputs are column-major raw storage (`(i, j)` at `j·n + i`); matrix results are
column-major. Do not edit by hand.
-/
import {imp}

namespace {ns}

open StaticVectors AbstractTensors

variable \{α : Type} [Coeff α]
"

/-- The determinant family and the characteristic polynomials. -/
unsafe def unrolled : IO Unit := do
  IO.println (header "Straight-line forms of the determinant family of `n × n` grade-1 operators, `n = 2 … 6`:
`det`, the Cramer `inv`, the `adjugate`, the Cramer `solve` (Julia `value(T) \\ v`) and the
characteristic polynomial." "Grassmann.Forms.Mat" "Grassmann.Forms.Unrolled"
    " > Grassmann/Forms/Unrolled.lean")
  IO.println "open Grassmann.Forms\n"
  let rd := "Mat.rd"
  for n in [5, 6] do
    let T := symOp n
    IO.println (defn rd s!"det{n}" s!"`det` of a `{n} × {n}` operator (the wedge of its columns)."
      "(raw : Packed.Arr α) : α" (n * n) 0 #[T.detGeneric] true)
  for n in [3, 4, 5, 6] do
    let T := symOp n
    IO.println (defn rd s!"inv{n}" s!"The Cramer inverse of a `{n} × {n}` operator (`invSquareGeneric`), column-major."
      "[Div α] (raw : Packed.Arr α) : Packed.Arr α" (n * n) 0 T.invSquareGeneric.mat.v.data false)
  for n in [2, 3, 4, 5, 6] do
    let T := symOp n
    IO.println (defn rd s!"adjugate{n}" s!"The adjugate of a `{n} × {n}` operator (Julia's Cramer rows), column-major."
      "(raw : Packed.Arr α) : Packed.Arr α" (n * n) 0 T.adjugateGeneric.mat.v.data false)
  for n in [2, 3, 4, 5, 6] do
    let T := symOp n
    IO.println (defn rd s!"solve{n}" s!"The Cramer solve (Julia `value(T) \\ v`) of a `{n} × {n}` operator."
      "[Div α] (raw vv : Packed.Arr α) : Packed.Arr α" (n * n) n (T.solveGeneric (symVec n)).v.data false)
  for n in [3, 4, 5, 6] do
    let T := symOp n
    IO.println (defn rd s!"characteristic{n}"
      s!"The characteristic polynomial's lower coefficients `(c₀, …, c₋₁)` of a `{n} × {n}` operator."
      "[Div α] (raw : Packed.Arr α) : Packed.Arr α" (n * n) 0 T.characteristicGeneric.v.data false)
  IO.println "end Grassmann.Forms.Unrolled"

/-- The raw read of `UnrolledMat` (`Mat.rd`, which that module cannot import). -/
def rdDef : String := "/-- Checked read of raw packed storage (zero out of range; the generated indices are in
range). -/
@[inline] def rd (a : Packed.Arr α) (i : Nat) : α :=
  if h : i < Packed.size a then Packed.get a ⟨i, h⟩ else Coeff.zero
"

/-- The `5 × 5` and `6 × 6` products. -/
unsafe def unrolledMat : IO Unit := do
  IO.println (header "Straight-line `A x` and `A B` of `5 × 5` and `6 × 6` column-major matrices (Julia's
`matmul`: every entry the first product plus the others, left to right)."
    "Grassmann.Types.Dims" "Grassmann.Forms.UnrolledMat" " mat > Grassmann/Forms/UnrolledMat.lean")
  IO.println rdDef
  for n in [5, 6] do
    let A := (symOp n).mat
    IO.println (defn "rd" s!"mulVec{n}" s!"`A x` of a `{n} × {n}` matrix."
      "(raw vv : Packed.Arr α) : Packed.Arr α" (n * n) n (A.mulVecGeneric (symVec n).v).data false)
  for n in [5, 6] do
    let A := (symOp n).mat
    let B := (symOp2 n).mat
    IO.println (defn "rd" s!"mul{n}" s!"`A B` of `{n} × {n}` matrices, column-major."
      "(raw vv : Packed.Arr α) : Packed.Arr α" (n * n) (n * n) (A.mulGeneric B).v.data false)
  IO.println "end Grassmann.Forms.UnrolledMat"

end GenUnrolled

unsafe def main (args : List String) : IO Unit :=
  if args.contains "mat" then GenUnrolled.unrolledMat else GenUnrolled.unrolled
