import Tests.Forms.Common

/-!
# The generated determinant family is the generic algorithm

`Grassmann.Forms.Unrolled` (generated by `oracle/forms/GenUnrolled.lean`) must be
**bit-identical** to the generic algorithms it was generated from (`detGeneric`,
`invSquareGeneric`, `adjugateGeneric`, `solveGeneric`): for random `Float` operators of
`n = 2 … 6` (including exact zeros, negative zeros and integers), every coefficient of
`det`, `inv`, `adjugate` and `solve` is compared by its bits (NaNs identified). The Julia
goldens of `forms/exact` and `forms/float` then cover the generated forms too.
-/

namespace Tests.FormsTests.Unrolled

open Lean Tests.Units Grassmann DirectSum StaticVectors Tests.FormsTests JuliaBase

/-- Bitwise equality (NaNs identified). -/
def same (a b : Float) : Bool := (a.isNaN && b.isNaN) || a.toBits == b.toBits

/-- Bitwise equality of two coefficient vectors. -/
def sameAll (a b : FloatArray) : Bool :=
  a.size == b.size && (List.range a.size).all fun i => same (a.get! i) (b.get! i)

/-- A SplitMix64 step. -/
def mix (s : UInt64) : UInt64 × UInt64 :=
  let s := s + 0x9e3779b97f4a7c15
  let z := (s ^^^ (s >>> 30)) * 0xbf58476d1ce4e5b9
  let z := (z ^^^ (z >>> 27)) * 0x94d049bb133111eb
  (z ^^^ (z >>> 31), s)

/-- An entry: mostly uniform in `[-2, 2)`, sometimes `0`, `-0.0` or a small integer. -/
def entry (z : UInt64) : Float :=
  match z % 16 with
  | 0 => 0
  | 1 => -0.0
  | 2 => ((z >>> 8) % 7).toFloat - 3
  | _ => ((z >>> 11).toFloat * 1.1102230246251565e-16) * 4 - 2

/-- `k` entries from a seed. -/
def entries (k : Nat) (seed : UInt64) : Array Float := Id.run do
  let mut s := seed
  let mut out := #[]
  for _ in [0:k] do
    let (z, s') := mix s
    s := s'
    out := out.push (entry z)
  return out

/-- The checks for one operator of `ℝⁿ`. -/
def check (n : Nat) (t : Tally) (seed : UInt64) : Tally := Id.run do
  let xs := entries (n * n + n) seed
  let V := En n
  let T : Endomorphism V (.chain 1) Float := TensorOperator.ofFn fun i j => xs[j.1 * n + i.1]!
  let v : Chain V 1 Float := ⟨Values.ofFn fun i => xs[n * n + i.1]!⟩
  let w := fun (s : String) => fun (_ : Unit) => s!"unrolled n={n} seed={seed} {s}"
  let mut t := t
  t := t.ok (same T.det T.detGeneric) (w s!"det {T.det} vs {T.detGeneric}")
  t := t.ok (sameAll T.adjugate.mat.v.data T.adjugateGeneric.mat.v.data) (w "adjugate")
  t := t.ok (sameAll (T.solve v).v.data (T.solveGeneric v).v.data) (w "solve")
  if n ≥ 5 then
    t := t.ok (sameAll T.invSquare.mat.v.data T.invSquareGeneric.mat.v.data) (w "inv")
  return t

/-- Run the suite. -/
def suite : IO Tally := do
  let mut t := Tally.new "forms/unrolled"
  for n in [2, 3, 4, 5, 6] do
    for k in [0:60] do
      t := check n t (0xC0FFEE + (n * 1000 + k).toUInt64)
  return t

end Tests.FormsTests.Unrolled
