/-
Julia's display of `Values` against `Tests/AbstractTensors/oracle/values_show.json` (generated by
`Tests/AbstractTensors/oracle/gen_show.jl`): `repr` (compact form with the eltype prefix) and the
`text/plain` display (header, aligned elements), plus the `vals![…]` literal.
-/
import StaticVectors
import Tests.AbstractTensors.Harness
import Lean.Data.Json

namespace Tests.AbstractTensors.ValuesShow

open StaticVectors JuliaBase Lean

-- the README quick start `Values(1, 2, 3)`
example : (vals![(1 : Int), 2, 3]).toList = [1, 2, 3] := by decide
#guard (vals![(1 : Int), 2, 3]).sum == 6
#guard Values.showRepr (vals![(1.0 : Float), 2.0, 3.0]) == "[1.0, 2.0, 3.0]"
#guard (Values.ones : Values Int 3).toList == [1, 1, 1]

/-- The Lean value of each golden case: `(repr, text/plain)`. -/
def lean : List (String × String × String) :=
  let e {α : Type} [Packed α] [JuliaEltype α] {n : Nat} (v : Values α n) := (Values.showRepr v, Values.showPlain v)
  let c (a b : Float) : Complex Float := ⟨a, b⟩
  let ci (a b : Int) : Complex Int := ⟨a, b⟩
  [ ("f64", e (vals![(0.5 : Float), 1 / 3, 1.0e10, 1.0e-5, -0.0, 2.0])),
    ("f64special", e (vals![(0.0 / 0.0 : Float), 1.0 / 0.0, -1.0 / 0.0])),
    ("f64align", e (vals![(-1.5 : Float), 2.25, 100.0])),
    ("f64two", e (vals![(1.5 : Float), -2.0])),
    ("int", e (vals![(1 : Int), 2, 3])),
    ("intneg", e (vals![(-10 : Int), 2, 300])),
    ("f32", e (vals![(1.5 : Float32), 2.0, 0.1])),
    ("bool", e (vals![true, false])),
    ("rat", e (vals![(1 / 2 : Rat), -3 / 4])),
    ("cint", e (vals![ci 1 2, ci 3 0])),
    ("cf64", e (vals![c 1.0 2.0, c (-0.0) (-1.5)])),
    ("u8", e (vals![(3 : UInt8), 4])),
    ("nested", e (vals![vals![(1 : Int), 2], vals![(3 : Int), 4]])),
    ("empty_int", e (Values.ofFn (n := 0) fun _ => (0 : Int))),
    ("empty_f64", e (Values.ofFn (n := 0) fun _ => (0 : Float))),
    ("single", e (vals![(42.0 : Float)])) ]

/-- The suite. -/
def suite : TestM Unit := do
  let j ← IO.FS.readFile "Tests/AbstractTensors/oracle/values_show.json"
  match Json.parse j with
  | .error e => check false fun _ => s!"values_show.json: {e}"
  | .ok root =>
    for c in (root.getObjValD "cases").getArr?.toOption.getD #[] do
      let nm := (c.getObjValD "name").getStr?.toOption.getD ""
      let r := (c.getObjValD "repr").getStr?.toOption.getD ""
      let p := (c.getObjValD "plain").getStr?.toOption.getD ""
      match lean.lookup nm with
      | none => check false fun _ => s!"{nm}: no Lean case"
      | some (lr, lp) =>
        check (lr == r) fun _ => s!"{nm} repr: {lr.quote} vs {r.quote}"
        check (lp == p) fun _ => s!"{nm} text/plain: {lp.quote} vs {p.quote}"

end Tests.AbstractTensors.ValuesShow
