import Tests.Adapode.Tables
import Tests.Adapode.Fixed
import Tests.Adapode.Adaptive
import Tests.Adapode.Chaos
import Tests.Adapode.Flow
import Tests.Adapode.Geodesic
import Tests.Adapode.Props

/-!
Adapode test aggregator.

`Tests.Adapode.run` compares the ODE port with the Julia oracle (`oracle/golden/adapode/*`,
regenerated by `oracle/adapode/gen.jl`) and runs the property checks.
-/

open Tests.Small

namespace Tests.Adapode

/-- Run every Adapode suite; returns `(passed, failed)`. -/
def run : IO (Nat × Nat) := runSuite "Adapode" do
  Tests.AdapodeTests.Tables.run
  Tests.AdapodeTests.Fixed.run
  Tests.AdapodeTests.Adaptive.run
  Tests.AdapodeTests.Chaos.run
  Tests.AdapodeTests.FlowTests.run
  Tests.AdapodeTests.Geodesics.run
  Tests.AdapodeTests.Props.run

end Tests.Adapode
