import Tests.FlowGeometry.Profiles
import Tests.FlowGeometry.Airfoils
import Tests.FlowGeometry.Meshes

/-!
FlowGeometry test aggregator.

`Tests.FlowGeometry.run` compares the port with the Julia oracle (`oracle/golden/flowgeometry/*`,
regenerated by `oracle/flowgeometry/gen.jl`), bit for bit.
-/

open Tests.Small

namespace Tests.FlowGeometry

/-- Run every FlowGeometry suite; returns `(passed, failed)`. -/
def run : IO (Nat × Nat) := runSuite "FlowGeometry" do
  Tests.FlowGeometryTests.Profiles.runInternals
  Tests.FlowGeometryTests.Profiles.run
  Tests.FlowGeometryTests.Airfoils.run
  Tests.FlowGeometryTests.Meshes.run

end Tests.FlowGeometry
