import Tests.MeshTopology.Misc
import Tests.MeshTopology.Quotient
import Tests.MeshTopology.Simplex
import Tests.MeshTopology.Lagrange
import Tests.MeshTopology.Properties
import Tests.MeshTopology.Static

/-!
MeshTopology test aggregator.

`Tests.MeshTopology.run` compares the port with the Julia oracle (`oracle/golden/meshtopology/*`,
regenerated by `oracle/meshtopology/gen.jl`) and runs the randomized property tests. Golden entries
where both upstream and fixed Julia throw are not checked; their count is printed.
-/

open Lean Tests.Small

namespace Tests.MeshTopology

/-- Number of golden values whose expected (fixed) value is a Julia exception. -/
partial def bothErrors (j : Json) : Nat :=
  match j with
  | .obj _ =>
    match j.getObjVal? "fixed" with
    | .ok v => if isError v then 1 else bothErrors v
    | .error _ =>
      if isError j then 1
      else (j.getObj?.toOption.map fun o => o.toArray.foldl (fun acc (_, v) => acc + bothErrors v) 0).getD 0
  | .arr a => a.foldl (fun acc v => acc + bothErrors v) 0
  | _ => 0

/-- Run every MeshTopology suite; returns `(passed, failed)`. -/
def run : IO (Nat × Nat) := do
  let r ← runSuite "MeshTopology" do
    Misc.run
    Quotient.run
    Simplex.run
    Lagrange.run
    Properties.run
  let mut skipped := 0
  for f in ["misc", "product", "quotient", "cross", "simplex", "lagrange"] do
    skipped := skipped + bothErrors (← readJson s!"oracle/golden/meshtopology/{f}.json")
  IO.println s!"MeshTopology: {skipped} golden values throw in upstream and fixed Julia (not compared)"
  return r

end Tests.MeshTopology
