import Tests.Wilkinson.Exprval
import Tests.Wilkinson.Reduce
import Tests.Wilkinson.Ranges
import Tests.Wilkinson.Kernels
import Tests.Wilkinson.Stieltjes
import Tests.Wilkinson.Comparison
import Tests.Wilkinson.Props

/-!
Test aggregator for the Wilkinson port: Julia-oracle goldens
(`oracle/golden/wilkinson/`, regenerated by `oracle/wilkinson/gen.jl`), property
tests and compile-time checks. Run from the package root (the goldens are read
by relative path).
-/

namespace Tests.Wilkinson

open Tests.Golden

/-- Run every Wilkinson suite; returns `(passed, failed)`. -/
def run : IO (Nat × Nat) := do
  let suites : List (String × TestM Unit) :=
    [("Wilkinson.exprval", Exprval.suite), ("Wilkinson.reduce", ReduceForms.suite),
     ("Wilkinson.ranges", Ranges.suite), ("Wilkinson.kernels", Kernels.suite),
     ("Wilkinson.stieltjes", Stieltjes.suite), ("Wilkinson.comparison", Comparison.suite),
     ("Wilkinson.props", Props.suite)]
  let mut total := (0, 0)
  for (label, s) in suites do
    let (p, f) ← runSuite label s
    total := (total.1 + p, total.2 + f)
  return total

end Tests.Wilkinson
