# Colormaps the gallery needs that LeanPlot does not ship (Makie `to_colormap` tables), and a
# consistency report for the ones it does.
#
#   julia --startup-file=no --project=oracle oracle/gallery/colormaps.jl
#
# Writes gallery/Gallery/ColormapData.lean in LeanPlot's `ColormapData` format (`r g b` per
# entry, each channel the 8 hex digits of its Float32 bit pattern) and prints, for every
# colormap the gallery uses, whether LeanPlot's table matches Makie's bit for bit.
using CairoMakie

const ROOT = normpath(joinpath(@__DIR__, "..", ".."))
const EXTRA = [:gist_earth]
const USED = [:gnuplot, :gist_earth, :jet, :cubehelix, :viridis]

f32hex(x) = string(reinterpret(UInt32, Float32(x)), base = 16, pad = 8)
table(nm) = join(f32hex(c.r) * f32hex(c.g) * f32hex(c.b) for c in Makie.to_colormap(nm))

open(joinpath(ROOT, "gallery", "Gallery", "ColormapData.lean"), "w") do io
    println(io, """/-
GENERATED by oracle/gallery/colormaps.jl from `Makie.to_colormap` (Makie $(pkgversion(Makie))):
colormaps the gallery uses that LeanPlot does not ship, in LeanPlot's `ColormapData` format
(`r g b` per entry, every channel the 8 hex digits of its `Float32` bit pattern). Do not edit.
-/
import LeanPlot

namespace Gallery.ColormapData
""")
    for nm in EXTRA
        println(io, "/-- `:$(nm)` ($(length(Makie.to_colormap(nm))) entries). -/")
        println(io, "def cm_$(nm) : String :=\n  \"$(table(nm))\"\n")
    end
    println(io, "/-- The extra tables by Makie name. -/")
    println(io, "def all : Array (String × String) := #[")
    println(io, join(["  (\"$(nm)\", cm_$(nm))" for nm in EXTRA], ",\n"))
    println(io, "]\n")
    println(io, "/-- An extra colormap by Makie name. -/")
    println(io, "def named? (name : String) : Option LeanPlot.Colormap :=")
    println(io, "  (all.find? (·.1 == name)).map fun (n, h) => LeanPlot.Colormap.ofF32Hex n h\n")
    println(io, "end Gallery.ColormapData")
end
for nm in USED
    println(rpad(string(nm), 12), length(Makie.to_colormap(nm)), " entries")
end
println("wrote gallery/Gallery/ColormapData.lean")
