# Emits JuliaBase/MathTables.lean: Julia's Base.Math lookup tables as Lean literals.
#   julia --startup-file=no Tests/JuliaBase/gen_tables.jl > JuliaBase/MathTables.lean
const JT = Base.Math.J_TABLE
const LT = Base.Math.t_log_table_compact
const TL = Base.Math.t_log_Float64
const TL32 = Base.Math.t_log_Float32
hex(u) = "0x" * string(u, base = 16, pad = 16)
println("/-!")
println("# Julia `Base.Math` lookup tables")
println()
println("Generated by `Tests/JuliaBase/gen_tables.jl` from Julia $(VERSION) (`Base.Math.J_TABLE`,")
println("`Base.Math.t_log_table_compact`, `Base.Math.t_log_Float64`, `Base.Math.t_log_Float32`). Floats")
println("are stored as IEEE bit patterns so the tables are bit-identical to Julia's. They drive the")
println("kernels of `JuliaBase.Math`.")
println("-/")
println()
println("namespace JuliaBase.Math")
println()
println("/-- Julia `Base.Math.J_TABLE` (`base/special/exp.jl:125`): `2^(j/256)` in extended precision. -/")
println("def jTable : Array UInt64 := #[")
for (i, j) in enumerate(JT)
    print("  ", hex(j), i < length(JT) ? "," : "", i % 4 == 0 ? "\n" : "")
end
println("]")
println()
println("/-- Julia `Base.Math.t_log_table_compact` (`base/special/log.jl:416`), packed `(invc|logc)` words. -/")
println("def logTableT : Array UInt64 := #[")
for (i, (t, tail)) in enumerate(LT)
    print("  ", hex(t), i < length(LT) ? "," : "", i % 4 == 0 ? "\n" : "")
end
println("]")
println()
println("/-- Low parts `logctail` of `t_log_table_compact`, as IEEE bit patterns. -/")
println("def logTableTail : Array UInt64 := #[")
for (i, (t, tail)) in enumerate(LT)
    print("  ", hex(reinterpret(UInt64, tail)), i < length(LT) ? "," : "", i % 4 == 0 ? "\n" : "")
end
println("]")
println()
println("/-- Julia `Base.Math.t_log_Float64` (`base/special/log.jl:29`): `(hi, lo)` of `log(1 + j/128)`, as IEEE bits. -/")
println("def logTable64 : Array (UInt64 × UInt64) := #[")
for (i, (h, l)) in enumerate(TL)
    print("  (", hex(reinterpret(UInt64, h)), ", ", hex(reinterpret(UInt64, l)), ")", i < length(TL) ? "," : "", i % 2 == 0 ? "\n" : "")
end
println("]")
println()
println("/-- Julia `Base.Math.t_log_Float32` (`base/special/log.jl:107`): `log(1 + j/128)` as `Float64` bits. -/")
println("def logTable32 : Array UInt64 := #[")
for (i, h) in enumerate(TL32)
    print("  ", hex(reinterpret(UInt64, h)), i < length(TL32) ? "," : "", i % 4 == 0 ? "\n" : "")
end
println("]")
println()
println("end JuliaBase.Math")
