import UnitSystems.Convert

/-!
# USQ dimensions as types

Reed's Unified System of Quantities has eleven base dimensions
`F M L T Q Θ N J A R C` (force, mass, length, time, charge, temperature,
molar amount, luminous flux, angle, rationalization, and the "nonstandard"
Lorentz dimension; Similitude `dimension.jl:144-156`). `Dim` is an exponent
vector over them, designed to live in **types**: Similitude indexes quantities
by it, so adding a length to a time is a type error and a product's dimension
is computed by type class resolution.

For that the representation matters. The elaborator's unifier runs type class
problems at `instances` transparency, where `Int` arithmetic does not reduce
but `Nat` literal arithmetic does. So each exponent `e` is stored as the natural
number `e + 2^20` and every operation is a `@[reducible]` definition on these
biased naturals; `USQ.F * USQ.L` then unifies with `Dim.energy` during
instance search, and the compiler erases the index entirely.

The 131 named dimensions (`Dim.energy`, `Dim.magneticflux`, …) are generated by
`oracle/unitsystems/dims.jl`, which recovers each quantity's exponents from the
Julia oracle by a log-linear fit and cross-checks them against Similitude's
`evaldim`; `UnitSystems.DimProofs` proves that every Lean conversion chain has
exactly this dimension.
-/

namespace UnitSystems

/-- The exponent bias `2^20`: an exponent `e` is stored as `e + dimBias`. -/
@[reducible] def dimBias : Nat := 1048576

/-- A USQ dimension: exponents of `F M L T Q Θ N J A R C`, each stored as
`exponent + 2^20` so that dimension arithmetic reduces during type class
resolution. Build values with `USQ.F`, `*`, `/`, `^` (or `Dim.ofInts`). -/
structure Dim where
  /-- force exponent (biased) -/
  F : Nat := dimBias
  /-- mass exponent (biased) -/
  M : Nat := dimBias
  /-- length exponent (biased) -/
  L : Nat := dimBias
  /-- time exponent (biased) -/
  T : Nat := dimBias
  /-- charge exponent (biased) -/
  Q : Nat := dimBias
  /-- temperature exponent (biased) -/
  Θ : Nat := dimBias
  /-- molar amount exponent (biased) -/
  N : Nat := dimBias
  /-- luminous flux exponent (biased) -/
  J : Nat := dimBias
  /-- angle exponent (biased) -/
  A : Nat := dimBias
  /-- rationalization exponent (biased) -/
  R : Nat := dimBias
  /-- nonstandard (inverse Lorentz) exponent (biased) -/
  C : Nat := dimBias
  deriving DecidableEq, Hashable, Inhabited

namespace Dim

/-- Dimension product (exponents add). -/
@[reducible] def mul (a b : Dim) : Dim :=
  ⟨a.F + b.F - dimBias, a.M + b.M - dimBias, a.L + b.L - dimBias, a.T + b.T - dimBias,
   a.Q + b.Q - dimBias, a.Θ + b.Θ - dimBias, a.N + b.N - dimBias, a.J + b.J - dimBias,
   a.A + b.A - dimBias, a.R + b.R - dimBias, a.C + b.C - dimBias⟩

/-- Dimension inverse (exponents negate). -/
@[reducible] def inv (a : Dim) : Dim :=
  ⟨2 * dimBias - a.F, 2 * dimBias - a.M, 2 * dimBias - a.L, 2 * dimBias - a.T,
   2 * dimBias - a.Q, 2 * dimBias - a.Θ, 2 * dimBias - a.N, 2 * dimBias - a.J,
   2 * dimBias - a.A, 2 * dimBias - a.R, 2 * dimBias - a.C⟩

/-- Halve every exponent (the dimension of a square root; exact when all
exponents are even, see `Dim.IsSquare`). -/
@[reducible] def half (a : Dim) : Dim :=
  ⟨(a.F + dimBias) / 2, (a.M + dimBias) / 2, (a.L + dimBias) / 2, (a.T + dimBias) / 2,
   (a.Q + dimBias) / 2, (a.Θ + dimBias) / 2, (a.N + dimBias) / 2, (a.J + dimBias) / 2,
   (a.A + dimBias) / 2, (a.R + dimBias) / 2, (a.C + dimBias) / 2⟩

/-- Dimensionless. -/
@[reducible] def one : Dim := {}

/-- Natural power, by repeated multiplication (reduces during unification). -/
@[reducible] def npow (a : Dim) : Nat → Dim
  | 0 => one
  | n + 1 => mul (npow a n) a

@[reducible] instance : Mul Dim := ⟨mul⟩
@[reducible] instance : Inv Dim := ⟨inv⟩
@[reducible] instance : Div Dim := ⟨fun a b => mul a (inv b)⟩
@[reducible] instance : HPow Dim Nat Dim := ⟨npow⟩
@[reducible] instance : One Dim := ⟨one⟩

/-- The exponents `[F, M, L, T, Q, Θ, N, J, A, R, C]` as integers. -/
def toInts (d : Dim) : List Int :=
  [d.F, d.M, d.L, d.T, d.Q, d.Θ, d.N, d.J, d.A, d.R, d.C].map fun (x : Nat) => (x : Int) - dimBias

/-- Build a dimension from integer exponents `[F, M, L, T, Q, Θ, N, J, A, R, C]`. -/
def ofInts (xs : List Int) : Dim :=
  let e (i : Nat) : Nat := (xs.getD i 0 + dimBias).toNat
  ⟨e 0, e 1, e 2, e 3, e 4, e 5, e 6, e 7, e 8, e 9, e 10⟩

/-- Every exponent is even: the dimension has a square root. -/
def IsSquare (d : Dim) : Prop := d.half * d.half = d

instance (d : Dim) : Decidable d.IsSquare := inferInstanceAs (Decidable (_ = _))

/-- The USQ letters, in order. -/
def letters : List String := ["F", "M", "L", "T", "Q", "Θ", "N", "J", "A", "R", "C"]

/-- Superscript integer (Julia `printexpo`). -/
def supInt (n : Int) : String :=
  let ds := "⁰¹²³⁴⁵⁶⁷⁸⁹".toList
  let digits := (toString n.natAbs).toList.map fun c => ds[c.toNat - '0'.toNat]!
  if n == 1 then "" else (if n < 0 then "⁻" else "") ++ String.ofList digits

/-- The dimension as a USQ monomial, as Similitude prints it (`ML²T⁻²`, `𝟙`). -/
protected def toString (d : Dim) : String :=
  let parts := (letters.zip d.toInts).filterMap fun (s, e) => if e == 0 then none else some (s ++ supInt e)
  if parts.isEmpty then "𝟙" else String.join parts

instance : ToString Dim := ⟨Dim.toString⟩
instance : Repr Dim := ⟨fun d _ => Dim.toString d⟩

end Dim

/-! The eleven USQ base dimensions (Julia `Similitude.USQ`). -/
namespace USQ
/-- dimensionless `𝟙` -/ @[reducible] def one : Dim := {}
/-- force -/ @[reducible] def F : Dim := { F := dimBias + 1 }
/-- mass -/ @[reducible] def M : Dim := { M := dimBias + 1 }
/-- length -/ @[reducible] def L : Dim := { L := dimBias + 1 }
/-- time -/ @[reducible] def T : Dim := { T := dimBias + 1 }
/-- charge -/ @[reducible] def Q : Dim := { Q := dimBias + 1 }
/-- temperature -/ @[reducible] def Θ : Dim := { Θ := dimBias + 1 }
/-- molar amount -/ @[reducible] def N : Dim := { N := dimBias + 1 }
/-- luminous flux -/ @[reducible] def J : Dim := { J := dimBias + 1 }
/-- angle -/ @[reducible] def A : Dim := { A := dimBias + 1 }
/-- rationalization (demagnetizing factor) -/ @[reducible] def R : Dim := { R := dimBias + 1 }
/-- nonstandard dimension (inverse Lorentz constant) -/ @[reducible] def C : Dim := { C := dimBias + 1 }
end USQ

namespace Dim

/-! ### The dimensions of the 131 convertible quantities (generated) -/

/-- `dimensionless`: `USQ.one` -/
@[reducible] def dimensionless : Dim := USQ.one
/-- `angle`: `USQ.A` -/
@[reducible] def angle : Dim := USQ.A
/-- `solidangle`: `USQ.A ^ 2` -/
@[reducible] def solidangle : Dim := USQ.A ^ 2
/-- `time`: `USQ.T` -/
@[reducible] def time : Dim := USQ.T
/-- `angulartime`: `USQ.T / USQ.A` -/
@[reducible] def angulartime : Dim := USQ.T / USQ.A
/-- `length`: `USQ.L` -/
@[reducible] def length : Dim := USQ.L
/-- `angularlength`: `USQ.L / USQ.A` -/
@[reducible] def angularlength : Dim := USQ.L / USQ.A
/-- `area`: `USQ.L ^ 2` -/
@[reducible] def area : Dim := USQ.L ^ 2
/-- `angulararea`: `USQ.L ^ 2 / USQ.A ^ 2` -/
@[reducible] def angulararea : Dim := USQ.L ^ 2 / USQ.A ^ 2
/-- `volume`: `USQ.L ^ 3` -/
@[reducible] def volume : Dim := USQ.L ^ 3
/-- `wavenumber`: `USQ.one / USQ.L` -/
@[reducible] def wavenumber : Dim := USQ.one / USQ.L
/-- `angularwavenumber`: `USQ.A / USQ.L` -/
@[reducible] def angularwavenumber : Dim := USQ.A / USQ.L
/-- `fuelefficiency`: `USQ.one / USQ.L ^ 2` -/
@[reducible] def fuelefficiency : Dim := USQ.one / USQ.L ^ 2
/-- `numberdensity`: `USQ.one / USQ.L ^ 3` -/
@[reducible] def numberdensity : Dim := USQ.one / USQ.L ^ 3
/-- `frequency`: `USQ.one / USQ.T` -/
@[reducible] def frequency : Dim := USQ.one / USQ.T
/-- `angularfrequency`: `USQ.A / USQ.T` -/
@[reducible] def angularfrequency : Dim := USQ.A / USQ.T
/-- `frequencydrift`: `USQ.one / USQ.T ^ 2` -/
@[reducible] def frequencydrift : Dim := USQ.one / USQ.T ^ 2
/-- `stagnance`: `USQ.T / USQ.L` -/
@[reducible] def stagnance : Dim := USQ.T / USQ.L
/-- `speed`: `USQ.L / USQ.T` -/
@[reducible] def speed : Dim := USQ.L / USQ.T
/-- `acceleration`: `USQ.L / USQ.T ^ 2` -/
@[reducible] def acceleration : Dim := USQ.L / USQ.T ^ 2
/-- `jerk`: `USQ.L / USQ.T ^ 3` -/
@[reducible] def jerk : Dim := USQ.L / USQ.T ^ 3
/-- `snap`: `USQ.L / USQ.T ^ 4` -/
@[reducible] def snap : Dim := USQ.L / USQ.T ^ 4
/-- `crackle`: `USQ.L / USQ.T ^ 5` -/
@[reducible] def crackle : Dim := USQ.L / USQ.T ^ 5
/-- `pop`: `USQ.L / USQ.T ^ 6` -/
@[reducible] def pop : Dim := USQ.L / USQ.T ^ 6
/-- `volumeflow`: `USQ.L ^ 3 / USQ.T` -/
@[reducible] def volumeflow : Dim := USQ.L ^ 3 / USQ.T
/-- `etendue`: `USQ.L ^ 2 * USQ.A ^ 2` -/
@[reducible] def etendue : Dim := USQ.L ^ 2 * USQ.A ^ 2
/-- `photonintensity`: `USQ.one / (USQ.T * USQ.A ^ 2)` -/
@[reducible] def photonintensity : Dim := USQ.one / (USQ.T * USQ.A ^ 2)
/-- `photonirradiance`: `USQ.T / USQ.L ^ 2` -/
@[reducible] def photonirradiance : Dim := USQ.T / USQ.L ^ 2
/-- `photonradiance`: `USQ.T / (USQ.L ^ 2 * USQ.A ^ 2)` -/
@[reducible] def photonradiance : Dim := USQ.T / (USQ.L ^ 2 * USQ.A ^ 2)
/-- `inertia`: `USQ.F * USQ.T ^ 2 / USQ.L` -/
@[reducible] def inertia : Dim := USQ.F * USQ.T ^ 2 / USQ.L
/-- `mass`: `USQ.M` -/
@[reducible] def mass : Dim := USQ.M
/-- `massflow`: `USQ.M / USQ.T` -/
@[reducible] def massflow : Dim := USQ.M / USQ.T
/-- `lineardensity`: `USQ.M / USQ.L` -/
@[reducible] def lineardensity : Dim := USQ.M / USQ.L
/-- `areadensity`: `USQ.M / USQ.L ^ 2` -/
@[reducible] def areadensity : Dim := USQ.M / USQ.L ^ 2
/-- `density`: `USQ.M / USQ.L ^ 3` -/
@[reducible] def density : Dim := USQ.M / USQ.L ^ 3
/-- `specificweight`: `USQ.F / USQ.L ^ 3` -/
@[reducible] def specificweight : Dim := USQ.F / USQ.L ^ 3
/-- `specificvolume`: `USQ.L ^ 3 / USQ.M` -/
@[reducible] def specificvolume : Dim := USQ.L ^ 3 / USQ.M
/-- `force`: `USQ.F` -/
@[reducible] def force : Dim := USQ.F
/-- `specificforce`: `USQ.F / USQ.M` -/
@[reducible] def specificforce : Dim := USQ.F / USQ.M
/-- `gravityforce`: `USQ.M * USQ.L / (USQ.F * USQ.T ^ 2)` -/
@[reducible] def gravityforce : Dim := USQ.M * USQ.L / (USQ.F * USQ.T ^ 2)
/-- `pressure`: `USQ.F / USQ.L ^ 2` -/
@[reducible] def pressure : Dim := USQ.F / USQ.L ^ 2
/-- `compressibility`: `USQ.L ^ 2 / USQ.F` -/
@[reducible] def compressibility : Dim := USQ.L ^ 2 / USQ.F
/-- `viscosity`: `USQ.F * USQ.T / USQ.L ^ 2` -/
@[reducible] def viscosity : Dim := USQ.F * USQ.T / USQ.L ^ 2
/-- `diffusivity`: `USQ.L ^ 2 / USQ.T` -/
@[reducible] def diffusivity : Dim := USQ.L ^ 2 / USQ.T
/-- `rotationalinertia`: `USQ.M * USQ.L ^ 2` -/
@[reducible] def rotationalinertia : Dim := USQ.M * USQ.L ^ 2
/-- `impulse`: `USQ.F * USQ.T` -/
@[reducible] def impulse : Dim := USQ.F * USQ.T
/-- `momentum`: `USQ.M * USQ.L / USQ.T` -/
@[reducible] def momentum : Dim := USQ.M * USQ.L / USQ.T
/-- `angularmomentum`: `USQ.F * USQ.L * USQ.T / USQ.A` -/
@[reducible] def angularmomentum : Dim := USQ.F * USQ.L * USQ.T / USQ.A
/-- `yank`: `USQ.M * USQ.L / USQ.T ^ 3` -/
@[reducible] def yank : Dim := USQ.M * USQ.L / USQ.T ^ 3
/-- `energy`: `USQ.F * USQ.L` -/
@[reducible] def energy : Dim := USQ.F * USQ.L
/-- `specificenergy`: `USQ.F * USQ.L / USQ.M` -/
@[reducible] def specificenergy : Dim := USQ.F * USQ.L / USQ.M
/-- `action`: `USQ.F * USQ.L * USQ.T` -/
@[reducible] def action : Dim := USQ.F * USQ.L * USQ.T
/-- `fluence`: `USQ.F / USQ.L` -/
@[reducible] def fluence : Dim := USQ.F / USQ.L
/-- `power`: `USQ.F * USQ.L / USQ.T` -/
@[reducible] def power : Dim := USQ.F * USQ.L / USQ.T
/-- `powerdensity`: `USQ.F / (USQ.L ^ 2 * USQ.T)` -/
@[reducible] def powerdensity : Dim := USQ.F / (USQ.L ^ 2 * USQ.T)
/-- `irradiance`: `USQ.F / (USQ.L * USQ.T)` -/
@[reducible] def irradiance : Dim := USQ.F / (USQ.L * USQ.T)
/-- `radiance`: `USQ.F / (USQ.L * USQ.T * USQ.A ^ 2)` -/
@[reducible] def radiance : Dim := USQ.F / (USQ.L * USQ.T * USQ.A ^ 2)
/-- `radiantintensity`: `USQ.F * USQ.L / (USQ.T * USQ.A ^ 2)` -/
@[reducible] def radiantintensity : Dim := USQ.F * USQ.L / (USQ.T * USQ.A ^ 2)
/-- `spectralflux`: `USQ.F / USQ.T` -/
@[reducible] def spectralflux : Dim := USQ.F / USQ.T
/-- `spectralexposure`: `USQ.F * USQ.T / USQ.L` -/
@[reducible] def spectralexposure : Dim := USQ.F * USQ.T / USQ.L
/-- `soundexposure`: `USQ.F ^ 2 * USQ.T / USQ.L ^ 4` -/
@[reducible] def soundexposure : Dim := USQ.F ^ 2 * USQ.T / USQ.L ^ 4
/-- `impedance`: `USQ.F * USQ.T / USQ.L ^ 5` -/
@[reducible] def impedance : Dim := USQ.F * USQ.T / USQ.L ^ 5
/-- `specificimpedance`: `USQ.F * USQ.T / USQ.L ^ 3` -/
@[reducible] def specificimpedance : Dim := USQ.F * USQ.T / USQ.L ^ 3
/-- `admittance`: `USQ.L ^ 5 / (USQ.F * USQ.T)` -/
@[reducible] def admittance : Dim := USQ.L ^ 5 / (USQ.F * USQ.T)
/-- `compliance`: `USQ.T ^ 2 / USQ.M` -/
@[reducible] def compliance : Dim := USQ.T ^ 2 / USQ.M
/-- `inertance`: `USQ.M / USQ.L ^ 4` -/
@[reducible] def inertance : Dim := USQ.M / USQ.L ^ 4
/-- `charge`: `USQ.Q` -/
@[reducible] def charge : Dim := USQ.Q
/-- `chargedensity`: `USQ.Q / USQ.L ^ 3` -/
@[reducible] def chargedensity : Dim := USQ.Q / USQ.L ^ 3
/-- `linearchargedensity`: `USQ.Q / USQ.L` -/
@[reducible] def linearchargedensity : Dim := USQ.Q / USQ.L
/-- `exposure`: `USQ.Q / USQ.M` -/
@[reducible] def exposure : Dim := USQ.Q / USQ.M
/-- `mobility`: `USQ.F * USQ.L ^ 3 / (USQ.T * USQ.Q)` -/
@[reducible] def mobility : Dim := USQ.F * USQ.L ^ 3 / (USQ.T * USQ.Q)
/-- `current`: `USQ.Q / USQ.T` -/
@[reducible] def current : Dim := USQ.Q / USQ.T
/-- `currentdensity`: `USQ.Q / (USQ.L ^ 2 * USQ.T)` -/
@[reducible] def currentdensity : Dim := USQ.Q / (USQ.L ^ 2 * USQ.T)
/-- `resistance`: `USQ.F * USQ.L * USQ.T / USQ.Q ^ 2` -/
@[reducible] def resistance : Dim := USQ.F * USQ.L * USQ.T / USQ.Q ^ 2
/-- `conductance`: `USQ.Q ^ 2 / (USQ.F * USQ.L * USQ.T)` -/
@[reducible] def conductance : Dim := USQ.Q ^ 2 / (USQ.F * USQ.L * USQ.T)
/-- `resistivity`: `USQ.F * USQ.L ^ 2 * USQ.T / USQ.Q ^ 2` -/
@[reducible] def resistivity : Dim := USQ.F * USQ.L ^ 2 * USQ.T / USQ.Q ^ 2
/-- `conductivity`: `USQ.Q ^ 2 / (USQ.F * USQ.L ^ 2 * USQ.T)` -/
@[reducible] def conductivity : Dim := USQ.Q ^ 2 / (USQ.F * USQ.L ^ 2 * USQ.T)
/-- `capacitance`: `USQ.Q ^ 2 / (USQ.F * USQ.L)` -/
@[reducible] def capacitance : Dim := USQ.Q ^ 2 / (USQ.F * USQ.L)
/-- `inductance`: `USQ.F * USQ.L * USQ.T ^ 2 / USQ.Q ^ 2` -/
@[reducible] def inductance : Dim := USQ.F * USQ.L * USQ.T ^ 2 / USQ.Q ^ 2
/-- `reluctance`: `USQ.Q ^ 2 * USQ.R / (USQ.F * USQ.L * USQ.T ^ 2 * USQ.C ^ 2)` -/
@[reducible] def reluctance : Dim := USQ.Q ^ 2 * USQ.R / (USQ.F * USQ.L * USQ.T ^ 2 * USQ.C ^ 2)
/-- `permeance`: `USQ.F * USQ.L * USQ.T ^ 2 * USQ.C ^ 2 / (USQ.Q ^ 2 * USQ.R)` -/
@[reducible] def permeance : Dim := USQ.F * USQ.L * USQ.T ^ 2 * USQ.C ^ 2 / (USQ.Q ^ 2 * USQ.R)
/-- `permittivity`: `USQ.Q ^ 2 * USQ.R / (USQ.F * USQ.L ^ 2)` -/
@[reducible] def permittivity : Dim := USQ.Q ^ 2 * USQ.R / (USQ.F * USQ.L ^ 2)
/-- `permeability`: `USQ.F * USQ.T ^ 2 * USQ.C ^ 2 / (USQ.Q ^ 2 * USQ.R)` -/
@[reducible] def permeability : Dim := USQ.F * USQ.T ^ 2 * USQ.C ^ 2 / (USQ.Q ^ 2 * USQ.R)
/-- `susceptibility`: `USQ.one / USQ.R` -/
@[reducible] def susceptibility : Dim := USQ.one / USQ.R
/-- `specificsusceptibility`: `USQ.L ^ 3 / (USQ.M * USQ.A * USQ.R)` -/
@[reducible] def specificsusceptibility : Dim := USQ.L ^ 3 / (USQ.M * USQ.A * USQ.R)
/-- `demagnetizingfactor`: `USQ.R` -/
@[reducible] def demagnetizingfactor : Dim := USQ.R
/-- `vectorpotential`: `USQ.F * USQ.T * USQ.C / USQ.Q` -/
@[reducible] def vectorpotential : Dim := USQ.F * USQ.T * USQ.C / USQ.Q
/-- `electricpotential`: `USQ.F * USQ.L / USQ.Q` -/
@[reducible] def electricpotential : Dim := USQ.F * USQ.L / USQ.Q
/-- `magneticpotential`: `USQ.Q * USQ.R / (USQ.T * USQ.C)` -/
@[reducible] def magneticpotential : Dim := USQ.Q * USQ.R / (USQ.T * USQ.C)
/-- `electricfield`: `USQ.F / USQ.Q` -/
@[reducible] def electricfield : Dim := USQ.F / USQ.Q
/-- `magneticfield`: `USQ.Q * USQ.R / (USQ.L * USQ.T * USQ.C)` -/
@[reducible] def magneticfield : Dim := USQ.Q * USQ.R / (USQ.L * USQ.T * USQ.C)
/-- `electricflux`: `USQ.F * USQ.L ^ 2 / USQ.Q` -/
@[reducible] def electricflux : Dim := USQ.F * USQ.L ^ 2 / USQ.Q
/-- `magneticflux`: `USQ.F * USQ.L * USQ.T * USQ.C / USQ.Q` -/
@[reducible] def magneticflux : Dim := USQ.F * USQ.L * USQ.T * USQ.C / USQ.Q
/-- `electricdisplacement`: `USQ.Q * USQ.R / USQ.L ^ 2` -/
@[reducible] def electricdisplacement : Dim := USQ.Q * USQ.R / USQ.L ^ 2
/-- `magneticfluxdensity`: `USQ.F * USQ.T * USQ.C / (USQ.L * USQ.Q)` -/
@[reducible] def magneticfluxdensity : Dim := USQ.F * USQ.T * USQ.C / (USQ.L * USQ.Q)
/-- `electricdipolemoment`: `USQ.L * USQ.Q` -/
@[reducible] def electricdipolemoment : Dim := USQ.L * USQ.Q
/-- `magneticdipolemoment`: `USQ.L ^ 2 * USQ.Q / (USQ.T * USQ.A * USQ.C)` -/
@[reducible] def magneticdipolemoment : Dim := USQ.L ^ 2 * USQ.Q / (USQ.T * USQ.A * USQ.C)
/-- `electricpolarizability`: `USQ.L * USQ.Q ^ 2 / USQ.F` -/
@[reducible] def electricpolarizability : Dim := USQ.L * USQ.Q ^ 2 / USQ.F
/-- `magneticpolarizability`: `USQ.L ^ 3 / (USQ.A * USQ.R)` -/
@[reducible] def magneticpolarizability : Dim := USQ.L ^ 3 / (USQ.A * USQ.R)
/-- `magneticmoment`: `USQ.F * USQ.L ^ 2 * USQ.T * USQ.C / USQ.Q` -/
@[reducible] def magneticmoment : Dim := USQ.F * USQ.L ^ 2 * USQ.T * USQ.C / USQ.Q
/-- `specificmagnetization`: `USQ.M * USQ.Q / (USQ.F * USQ.L ^ 2 * USQ.T * USQ.C)` -/
@[reducible] def specificmagnetization : Dim := USQ.M * USQ.Q / (USQ.F * USQ.L ^ 2 * USQ.T * USQ.C)
/-- `polestrength`: `USQ.L * USQ.Q / (USQ.T * USQ.A * USQ.C)` -/
@[reducible] def polestrength : Dim := USQ.L * USQ.Q / (USQ.T * USQ.A * USQ.C)
/-- `temperature`: `USQ.Θ` -/
@[reducible] def temperature : Dim := USQ.Θ
/-- `entropy`: `USQ.F * USQ.L / USQ.Θ` -/
@[reducible] def entropy : Dim := USQ.F * USQ.L / USQ.Θ
/-- `specificentropy`: `USQ.F * USQ.L / (USQ.M * USQ.Θ)` -/
@[reducible] def specificentropy : Dim := USQ.F * USQ.L / (USQ.M * USQ.Θ)
/-- `volumeheatcapacity`: `USQ.F / (USQ.L ^ 2 * USQ.Θ)` -/
@[reducible] def volumeheatcapacity : Dim := USQ.F / (USQ.L ^ 2 * USQ.Θ)
/-- `thermalconductivity`: `USQ.F / (USQ.T * USQ.Θ)` -/
@[reducible] def thermalconductivity : Dim := USQ.F / (USQ.T * USQ.Θ)
/-- `thermalconductance`: `USQ.F * USQ.L / (USQ.T * USQ.Θ)` -/
@[reducible] def thermalconductance : Dim := USQ.F * USQ.L / (USQ.T * USQ.Θ)
/-- `thermalresistivity`: `USQ.T * USQ.Θ / USQ.F` -/
@[reducible] def thermalresistivity : Dim := USQ.T * USQ.Θ / USQ.F
/-- `thermalresistance`: `USQ.T * USQ.Θ / (USQ.F * USQ.L)` -/
@[reducible] def thermalresistance : Dim := USQ.T * USQ.Θ / (USQ.F * USQ.L)
/-- `thermalexpansion`: `USQ.one / USQ.Θ` -/
@[reducible] def thermalexpansion : Dim := USQ.one / USQ.Θ
/-- `lapserate`: `USQ.Θ / USQ.L` -/
@[reducible] def lapserate : Dim := USQ.Θ / USQ.L
/-- `molarmass`: `USQ.M / USQ.N` -/
@[reducible] def molarmass : Dim := USQ.M / USQ.N
/-- `molality`: `USQ.N / USQ.M` -/
@[reducible] def molality : Dim := USQ.N / USQ.M
/-- `molaramount`: `USQ.N` -/
@[reducible] def molaramount : Dim := USQ.N
/-- `molarity`: `USQ.N / USQ.L ^ 3` -/
@[reducible] def molarity : Dim := USQ.N / USQ.L ^ 3
/-- `molarvolume`: `USQ.L ^ 3 / USQ.N` -/
@[reducible] def molarvolume : Dim := USQ.L ^ 3 / USQ.N
/-- `molarentropy`: `USQ.F * USQ.L / (USQ.Θ * USQ.N)` -/
@[reducible] def molarentropy : Dim := USQ.F * USQ.L / (USQ.Θ * USQ.N)
/-- `molarenergy`: `USQ.F * USQ.L / USQ.N` -/
@[reducible] def molarenergy : Dim := USQ.F * USQ.L / USQ.N
/-- `molarconductivity`: `USQ.Q ^ 2 / (USQ.F * USQ.T * USQ.N)` -/
@[reducible] def molarconductivity : Dim := USQ.Q ^ 2 / (USQ.F * USQ.T * USQ.N)
/-- `molarsusceptibility`: `USQ.L ^ 3 / (USQ.N * USQ.A * USQ.R)` -/
@[reducible] def molarsusceptibility : Dim := USQ.L ^ 3 / (USQ.N * USQ.A * USQ.R)
/-- `catalysis`: `USQ.N / USQ.T` -/
@[reducible] def catalysis : Dim := USQ.N / USQ.T
/-- `specificity`: `USQ.L ^ 3 / (USQ.T * USQ.N)` -/
@[reducible] def specificity : Dim := USQ.L ^ 3 / (USQ.T * USQ.N)
/-- `diffusionflux`: `USQ.T * USQ.N / USQ.L ^ 2` -/
@[reducible] def diffusionflux : Dim := USQ.T * USQ.N / USQ.L ^ 2
/-- `luminousflux`: `USQ.J` -/
@[reducible] def luminousflux : Dim := USQ.J
/-- `luminousintensity`: `USQ.J / USQ.A ^ 2` -/
@[reducible] def luminousintensity : Dim := USQ.J / USQ.A ^ 2
/-- `luminance`: `USQ.J / (USQ.L ^ 2 * USQ.A ^ 2)` -/
@[reducible] def luminance : Dim := USQ.J / (USQ.L ^ 2 * USQ.A ^ 2)
/-- `illuminance`: `USQ.J / USQ.L ^ 2` -/
@[reducible] def illuminance : Dim := USQ.J / USQ.L ^ 2
/-- `luminousenergy`: `USQ.T * USQ.J` -/
@[reducible] def luminousenergy : Dim := USQ.T * USQ.J
/-- `luminousexposure`: `USQ.T * USQ.J / USQ.L ^ 2` -/
@[reducible] def luminousexposure : Dim := USQ.T * USQ.J / USQ.L ^ 2
/-- `luminousefficacy`: `USQ.T * USQ.J / (USQ.F * USQ.L)` -/
@[reducible] def luminousefficacy : Dim := USQ.T * USQ.J / (USQ.F * USQ.L)

end Dim

/-- The USQ dimension of each convertible quantity (from the oracle, see `oracle/unitsystems/dims.jl`). -/
@[reducible] def Conv.dim : Conv → Dim
  | .dimensionless => Dim.dimensionless
  | .angle => Dim.angle
  | .solidangle => Dim.solidangle
  | .time => Dim.time
  | .angulartime => Dim.angulartime
  | .length => Dim.length
  | .angularlength => Dim.angularlength
  | .area => Dim.area
  | .angulararea => Dim.angulararea
  | .volume => Dim.volume
  | .wavenumber => Dim.wavenumber
  | .angularwavenumber => Dim.angularwavenumber
  | .fuelefficiency => Dim.fuelefficiency
  | .numberdensity => Dim.numberdensity
  | .frequency => Dim.frequency
  | .angularfrequency => Dim.angularfrequency
  | .frequencydrift => Dim.frequencydrift
  | .stagnance => Dim.stagnance
  | .speed => Dim.speed
  | .acceleration => Dim.acceleration
  | .jerk => Dim.jerk
  | .snap => Dim.snap
  | .crackle => Dim.crackle
  | .pop => Dim.pop
  | .volumeflow => Dim.volumeflow
  | .etendue => Dim.etendue
  | .photonintensity => Dim.photonintensity
  | .photonirradiance => Dim.photonirradiance
  | .photonradiance => Dim.photonradiance
  | .inertia => Dim.inertia
  | .mass => Dim.mass
  | .massflow => Dim.massflow
  | .lineardensity => Dim.lineardensity
  | .areadensity => Dim.areadensity
  | .density => Dim.density
  | .specificweight => Dim.specificweight
  | .specificvolume => Dim.specificvolume
  | .force => Dim.force
  | .specificforce => Dim.specificforce
  | .gravityforce => Dim.gravityforce
  | .pressure => Dim.pressure
  | .compressibility => Dim.compressibility
  | .viscosity => Dim.viscosity
  | .diffusivity => Dim.diffusivity
  | .rotationalinertia => Dim.rotationalinertia
  | .impulse => Dim.impulse
  | .momentum => Dim.momentum
  | .angularmomentum => Dim.angularmomentum
  | .yank => Dim.yank
  | .energy => Dim.energy
  | .specificenergy => Dim.specificenergy
  | .action => Dim.action
  | .fluence => Dim.fluence
  | .power => Dim.power
  | .powerdensity => Dim.powerdensity
  | .irradiance => Dim.irradiance
  | .radiance => Dim.radiance
  | .radiantintensity => Dim.radiantintensity
  | .spectralflux => Dim.spectralflux
  | .spectralexposure => Dim.spectralexposure
  | .soundexposure => Dim.soundexposure
  | .impedance => Dim.impedance
  | .specificimpedance => Dim.specificimpedance
  | .admittance => Dim.admittance
  | .compliance => Dim.compliance
  | .inertance => Dim.inertance
  | .charge => Dim.charge
  | .chargedensity => Dim.chargedensity
  | .linearchargedensity => Dim.linearchargedensity
  | .exposure => Dim.exposure
  | .mobility => Dim.mobility
  | .current => Dim.current
  | .currentdensity => Dim.currentdensity
  | .resistance => Dim.resistance
  | .conductance => Dim.conductance
  | .resistivity => Dim.resistivity
  | .conductivity => Dim.conductivity
  | .capacitance => Dim.capacitance
  | .inductance => Dim.inductance
  | .reluctance => Dim.reluctance
  | .permeance => Dim.permeance
  | .permittivity => Dim.permittivity
  | .permeability => Dim.permeability
  | .susceptibility => Dim.susceptibility
  | .specificsusceptibility => Dim.specificsusceptibility
  | .demagnetizingfactor => Dim.demagnetizingfactor
  | .vectorpotential => Dim.vectorpotential
  | .electricpotential => Dim.electricpotential
  | .magneticpotential => Dim.magneticpotential
  | .electricfield => Dim.electricfield
  | .magneticfield => Dim.magneticfield
  | .electricflux => Dim.electricflux
  | .magneticflux => Dim.magneticflux
  | .electricdisplacement => Dim.electricdisplacement
  | .magneticfluxdensity => Dim.magneticfluxdensity
  | .electricdipolemoment => Dim.electricdipolemoment
  | .magneticdipolemoment => Dim.magneticdipolemoment
  | .electricpolarizability => Dim.electricpolarizability
  | .magneticpolarizability => Dim.magneticpolarizability
  | .magneticmoment => Dim.magneticmoment
  | .specificmagnetization => Dim.specificmagnetization
  | .polestrength => Dim.polestrength
  | .temperature => Dim.temperature
  | .entropy => Dim.entropy
  | .specificentropy => Dim.specificentropy
  | .volumeheatcapacity => Dim.volumeheatcapacity
  | .thermalconductivity => Dim.thermalconductivity
  | .thermalconductance => Dim.thermalconductance
  | .thermalresistivity => Dim.thermalresistivity
  | .thermalresistance => Dim.thermalresistance
  | .thermalexpansion => Dim.thermalexpansion
  | .lapserate => Dim.lapserate
  | .molarmass => Dim.molarmass
  | .molality => Dim.molality
  | .molaramount => Dim.molaramount
  | .molarity => Dim.molarity
  | .molarvolume => Dim.molarvolume
  | .molarentropy => Dim.molarentropy
  | .molarenergy => Dim.molarenergy
  | .molarconductivity => Dim.molarconductivity
  | .molarsusceptibility => Dim.molarsusceptibility
  | .catalysis => Dim.catalysis
  | .specificity => Dim.specificity
  | .diffusionflux => Dim.diffusionflux
  | .luminousflux => Dim.luminousflux
  | .luminousintensity => Dim.luminousintensity
  | .luminance => Dim.luminance
  | .illuminance => Dim.illuminance
  | .luminousenergy => Dim.luminousenergy
  | .luminousexposure => Dim.luminousexposure
  | .luminousefficacy => Dim.luminousefficacy

end UnitSystems
