# Generator of UnitSystems/Text.lean: the name tables of UnitSystems' `text.jl`
# (`textconstants`, `textderived`, `textquantities`), the English names Julia's
# documentation uses for constants, derived units and quantities.
#   julia --startup-file=no --project=oracle oracle/unitsystems/text.jl
using UnitSystems
const US = UnitSystems
const OUT = joinpath(@__DIR__, "..", "..", "UnitSystems", "Text.lean")

esc(s) = replace(string(s), "\\" => "\\\\", "\"" => "\\\"")
function table(io, name, doc, d)
    println(io, "/-- ", doc, " -/")
    println(io, "def ", name, " : List (String × String) :=")
    ks = sort!(collect(keys(d)); by = string)
    for (i, k) in enumerate(ks)
        pre = i == 1 ? "  [" : "   "
        post = i == length(ks) ? "]" : ","
        println(io, pre, "(\"", esc(k), "\", \"", esc(d[k]), "\")", post)
    end
    println(io)
end

open(OUT, "w") do io
    println(io, """/-!
# Name tables (`text.jl`)

The English names UnitSystems' documentation gives its constants, derived units
and quantities (`UnitSystems.jl/src/text.jl`: `textconstants`, `textderived`,
`textquantities`), sorted by Julia name. Generated by `oracle/unitsystems/text.jl`
from UnitSystems $(pkgversion(US)); do not edit by hand.
-/

namespace UnitSystems.Text
""")
    table(io, "constants", "Julia `textconstants`: constants and physics quantities.", US.textconstants)
    table(io, "derived", "Julia `textderived`: derived units.", US.textderived)
    table(io, "quantities", "Julia `textquantities`: the convertible quantities.", US.textquantities)
    println(io, """/-- The English name of a constant, unit or quantity (in that order of lookup). -/
def name? (s : String) : Option String :=
  (constants.lookup s).orElse fun _ => (derived.lookup s).orElse fun _ => quantities.lookup s

end UnitSystems.Text""")
end
println("wrote ", OUT)
