# Emits Similitude/UnitNames.lean: Similitude's per-system unit-name registries
# (`unitgroup`/`unitlatex`, unitdim.jl) and base-dimension names (`dimtext`/`dimlatex`).
#   julia --startup-file=no --project=oracle oracle/similitude/registry.jl > Similitude/UnitNames.lean
# The registries are emitted as one string per system (records separated by newlines,
# key and name by a tab; keys are the image exponents doubled, space separated) so the
# Lean file elaborates instantly; `Similitude.Registry` parses them once at startup.
using Similitude
const S = Similitude
const US = S.UnitSystems
# exponents are halves at most: store them doubled
dbl(x) = (y = 2x; @assert isinteger(y); Int(y))
key(k) = join([dbl(a) for a in k.v], " ")
lesc(s) = replace(string(s), "\\" => "\\\\", "\"" => "\\\"", "\n" => "\\n", "\t" => "\\t")
function blob(d)
    ents = sort(collect(d), by = p -> (key(p.first), string(p.second)))
    for (k, v) in ents
        @assert !occursin('\t', v) && !occursin('\n', v)
    end
    "\"" * join([key(k) * "\\t" * lesc(v) for (k, v) in ents], "\\n") * "\""
end
println("/-!")
println("# Similitude unit-name tables (generated)")
println()
println("Generated by `oracle/similitude/registry.jl` from Similitude $(pkgversion(S)) (Julia $(VERSION)):")
println("the unit-name registries of `unitdim.jl` (keyed by the *image* of a dimension under a")
println("system's homomorphism) and the base-dimension names `dimtext`/`dimlatex` of")
println("`derived.jl:505-622`. Each registry is one string per system: newline-separated records")
println("`<doubled image exponents>\\t<name>`, parsed once by `Similitude.Registry`.")
println("-/")
println()
println("namespace Similitude")
println()
for (tab, sysd, regs, doc) in (("unitTextData", S.systemgroup, S.unitgroup, "Printed unit names"),
                              ("unitLatexData", S.systemlatex, S.unitlatex, "LaTeX unit names"))
    println("/-- $doc per system: `(unitname, records)` (`unitdim.jl:46-365`). -/")
    println("def $tab : Array (String × String) := #[")
    names = sort(collect(keys(sysd)); by = string)
    for (i, nam) in enumerate(names)
        println("  (\"", lesc(nam), "\",")
        println("   ", blob(regs[sysd[nam]]), ")", i < length(names) ? "," : "")
    end
    println("]")
    println()
end
println("/-- Base-dimension names per system: `(unitname, dimtext, all names are single characters, dimlatex)`. -/")
println("def dimTextTable : Array (String × Array String × Bool × Array String) := #[")
syss = vcat(collect(US.Systems), [:Unified])
for (i, s) in enumerate(syss)
    U = S.normal(getfield(S, s))
    dt = S.dimtext(U)
    ischar = eltype(dt) <: Char
    dl = S.dimlatex(U)
    println("  (\"", lesc(S.unitname(U)), "\", #[", join(["\"" * lesc(c) * "\"" for c in dt], ", "), "], ", ischar, ",")
    println("    #[", join(["\"" * lesc(c) * "\"" for c in dl], ", "), "])", i < length(syss) ? "," : "")
end
println("]")
println()
println("end Similitude")
