/-
The derived composite functions (`tanh`, `cot`, `sec`, `csc`, `coth`, `sech`, `csch`, the inverse
trigonometric and hyperbolic functions, `sinc`, `cosc`, `exp2`, `exp10`, `log2`, `log10`, and
`sqrt`/`cbrt` of a pseudo-couple) on every element kind that has no specialised form: AbstractTensors'
generic definitions (`AT:383-430`), evaluated on the element's multivector (Julia evaluates them on
the element, whose kinds combine to the same values; the result here is the `Multivector`).

GENERATED by `oracle/forms/gen_kinds.py` (`uv run oracle/forms/gen_kinds.py`), which lists the
(kind, function) pairs no other `Grassmann.Composite` module defines. Julia throws for several of
them (`asin`/`asinh` of a chain overflow the stack, `cot` of a couple and the phasor functions
hit an `UndefVarError`, `acos` of a spinor an `ErrorException`); here they are the functions'
values.
-/
import Grassmann.Composite.Phasor

namespace Grassmann

open DirectSum StaticVectors AbstractTensors Composite

variable {V : TensorBundle} [Kernels V]

namespace Single

variable {G : Nat}

/-- AbstractTensors `cot(t)` (`cos(t)/sin(t)`, `AT:410`) of a term, on its multivector. -/
@[specialize V] def cot (t : Single V G Float) : Multivector V Float := Multivector.cot (toMultivector t)

/-- AbstractTensors `sec(t)` (`inv(cos(t))`, `AT:411`) of a term, on its multivector. -/
@[specialize V] def sec (t : Single V G Float) : Multivector V Float := Multivector.sec (toMultivector t)

/-- AbstractTensors `csc(t)` (`inv(sin(t))`, `AT:412`) of a term, on its multivector. -/
@[specialize V] def csc (t : Single V G Float) : Multivector V Float := Multivector.csc (toMultivector t)

/-- AbstractTensors `coth(t)` (`cosh(t)/sinh(t)`, `AT:420`) of a term, on its multivector. -/
@[specialize V] def coth (t : Single V G Float) : Multivector V Float := Multivector.coth (toMultivector t)

/-- AbstractTensors `sech(t)` (`inv(cosh(t))`, `AT:415`) of a term, on its multivector. -/
@[specialize V] def sech (t : Single V G Float) : Multivector V Float := Multivector.sech (toMultivector t)

/-- AbstractTensors `csch(t)` (`inv(sinh(t))`, `AT:416`) of a term, on its multivector. -/
@[specialize V] def csch (t : Single V G Float) : Multivector V Float := Multivector.csch (toMultivector t)

/-- AbstractTensors `acos(t)` (`(-I) ⟑ log(t + I⟑sqrt(1 - t⟑t))`, `AT:426`) of a term, on its multivector. -/
@[specialize V] def acos (t : Single V G Float) : Multivector V Float := Multivector.acos (toMultivector t)

/-- AbstractTensors `acot(t)` (`((-I)/2) ⟑ (log(t - I) - log(t + I))`, `AT:428`) of a term, on its multivector. -/
@[specialize V] def acot (t : Single V G Float) : Multivector V Float := Multivector.acot (toMultivector t)

/-- AbstractTensors `asec(t)` (`acos(inv(t))`, `AT:413`) of a term, on its multivector. -/
@[specialize V] def asec (t : Single V G Float) : Multivector V Float := Multivector.asec (toMultivector t)

/-- AbstractTensors `acsc(t)` (`asin(inv(t))`, `AT:414`) of a term, on its multivector. -/
@[specialize V] def acsc (t : Single V G Float) : Multivector V Float := Multivector.acsc (toMultivector t)

/-- AbstractTensors `asech(t)` (`acosh(inv(t))`, `AT:417`) of a term, on its multivector. -/
@[specialize V] def asech (t : Single V G Float) : Multivector V Float := Multivector.asech (toMultivector t)

/-- AbstractTensors `acsch(t)` (`asinh(inv(t))`, `AT:418`) of a term, on its multivector. -/
@[specialize V] def acsch (t : Single V G Float) : Multivector V Float := Multivector.acsch (toMultivector t)

/-- AbstractTensors `sinc(t)` (`sinc(t)`, `AT:429`) of a term, on its multivector. -/
@[specialize V] def sinc (t : Single V G Float) : Multivector V Float := Multivector.sinc (toMultivector t)

/-- AbstractTensors `cosc(t)` (`cosc(t)`, `AT:430`) of a term, on its multivector. -/
@[specialize V] def cosc (t : Single V G Float) : Multivector V Float := Multivector.cosc (toMultivector t)

/-- AbstractTensors `exp2(t)` (`exp(log(2)·t)`, `AT:384`) of a term, on its multivector. -/
@[specialize V] def exp2 (t : Single V G Float) : Multivector V Float := Multivector.exp2 (toMultivector t)

/-- AbstractTensors `exp10(t)` (`exp(log(10)·t)`, `AT:384`) of a term, on its multivector. -/
@[specialize V] def exp10 (t : Single V G Float) : Multivector V Float := Multivector.exp10 (toMultivector t)

/-- AbstractTensors `log2(t)` (`log2(ℯ)·log(t)`, `AT:383`) of a term, on its multivector. -/
@[specialize V] def log2 (t : Single V G Float) : Multivector V Float := Multivector.log2 (toMultivector t)

/-- AbstractTensors `log10(t)` (`log10(ℯ)·log(t)`, `AT:383`) of a term, on its multivector. -/
@[specialize V] def log10 (t : Single V G Float) : Multivector V Float := Multivector.log10 (toMultivector t)

end Single

namespace Chain

variable {G : Nat}

/-- AbstractTensors `cot(t)` (`cos(t)/sin(t)`, `AT:410`) of a chain, on its multivector. -/
@[specialize V] def cot (t : Chain V G Float) : Multivector V Float := Multivector.cot (toMultivector t)

/-- AbstractTensors `sec(t)` (`inv(cos(t))`, `AT:411`) of a chain, on its multivector. -/
@[specialize V] def sec (t : Chain V G Float) : Multivector V Float := Multivector.sec (toMultivector t)

/-- AbstractTensors `csc(t)` (`inv(sin(t))`, `AT:412`) of a chain, on its multivector. -/
@[specialize V] def csc (t : Chain V G Float) : Multivector V Float := Multivector.csc (toMultivector t)

/-- AbstractTensors `coth(t)` (`cosh(t)/sinh(t)`, `AT:420`) of a chain, on its multivector. -/
@[specialize V] def coth (t : Chain V G Float) : Multivector V Float := Multivector.coth (toMultivector t)

/-- AbstractTensors `sech(t)` (`inv(cosh(t))`, `AT:415`) of a chain, on its multivector. -/
@[specialize V] def sech (t : Chain V G Float) : Multivector V Float := Multivector.sech (toMultivector t)

/-- AbstractTensors `csch(t)` (`inv(sinh(t))`, `AT:416`) of a chain, on its multivector. -/
@[specialize V] def csch (t : Chain V G Float) : Multivector V Float := Multivector.csch (toMultivector t)

/-- AbstractTensors `asin(t)` (`(-I) ⟑ log(I⟑t + sqrt(1 - t⟑t))`, `AT:425`) of a chain, on its multivector. -/
@[specialize V] def asin (t : Chain V G Float) : Multivector V Float := Multivector.asin (toMultivector t)

/-- AbstractTensors `acos(t)` (`(-I) ⟑ log(t + I⟑sqrt(1 - t⟑t))`, `AT:426`) of a chain, on its multivector. -/
@[specialize V] def acos (t : Chain V G Float) : Multivector V Float := Multivector.acos (toMultivector t)

/-- AbstractTensors `atan(t)` (`((-I)/2) ⟑ (log(1 + I⟑t) - log(1 - I⟑t))`, `AT:427`) of a chain, on its multivector. -/
@[specialize V] def atan (t : Chain V G Float) : Multivector V Float := Multivector.atan (toMultivector t)

/-- AbstractTensors `acot(t)` (`((-I)/2) ⟑ (log(t - I) - log(t + I))`, `AT:428`) of a chain, on its multivector. -/
@[specialize V] def acot (t : Chain V G Float) : Multivector V Float := Multivector.acot (toMultivector t)

/-- AbstractTensors `asec(t)` (`acos(inv(t))`, `AT:413`) of a chain, on its multivector. -/
@[specialize V] def asec (t : Chain V G Float) : Multivector V Float := Multivector.asec (toMultivector t)

/-- AbstractTensors `acsc(t)` (`asin(inv(t))`, `AT:414`) of a chain, on its multivector. -/
@[specialize V] def acsc (t : Chain V G Float) : Multivector V Float := Multivector.acsc (toMultivector t)

/-- AbstractTensors `asinh(t)` (`log(t + sqrt(1 + t⟑t))`, `AT:421`) of a chain, on its multivector. -/
@[specialize V] def asinh (t : Chain V G Float) : Multivector V Float := Multivector.asinh (toMultivector t)

/-- AbstractTensors `acosh(t)` (`log(t + sqrt(t⟑t - 1))`, `AT:422`) of a chain, on its multivector. -/
@[specialize V] def acosh (t : Chain V G Float) : Multivector V Float := Multivector.acosh (toMultivector t)

/-- AbstractTensors `atanh(t)` (`(log(1+t) - log(1-t))/2`, `AT:423`) of a chain, on its multivector. -/
@[specialize V] def atanh (t : Chain V G Float) : Multivector V Float := Multivector.atanh (toMultivector t)

/-- AbstractTensors `acoth(t)` (`(log(t+1) - log(t-1))/2`, `AT:424`) of a chain, on its multivector. -/
@[specialize V] def acoth (t : Chain V G Float) : Multivector V Float := Multivector.acoth (toMultivector t)

/-- AbstractTensors `asech(t)` (`acosh(inv(t))`, `AT:417`) of a chain, on its multivector. -/
@[specialize V] def asech (t : Chain V G Float) : Multivector V Float := Multivector.asech (toMultivector t)

/-- AbstractTensors `acsch(t)` (`asinh(inv(t))`, `AT:418`) of a chain, on its multivector. -/
@[specialize V] def acsch (t : Chain V G Float) : Multivector V Float := Multivector.acsch (toMultivector t)

/-- AbstractTensors `sinc(t)` (`sinc(t)`, `AT:429`) of a chain, on its multivector. -/
@[specialize V] def sinc (t : Chain V G Float) : Multivector V Float := Multivector.sinc (toMultivector t)

/-- AbstractTensors `cosc(t)` (`cosc(t)`, `AT:430`) of a chain, on its multivector. -/
@[specialize V] def cosc (t : Chain V G Float) : Multivector V Float := Multivector.cosc (toMultivector t)

/-- AbstractTensors `exp2(t)` (`exp(log(2)·t)`, `AT:384`) of a chain, on its multivector. -/
@[specialize V] def exp2 (t : Chain V G Float) : Multivector V Float := Multivector.exp2 (toMultivector t)

/-- AbstractTensors `exp10(t)` (`exp(log(10)·t)`, `AT:384`) of a chain, on its multivector. -/
@[specialize V] def exp10 (t : Chain V G Float) : Multivector V Float := Multivector.exp10 (toMultivector t)

/-- AbstractTensors `log2(t)` (`log2(ℯ)·log(t)`, `AT:383`) of a chain, on its multivector. -/
@[specialize V] def log2 (t : Chain V G Float) : Multivector V Float := Multivector.log2 (toMultivector t)

/-- AbstractTensors `log10(t)` (`log10(ℯ)·log(t)`, `AT:383`) of a chain, on its multivector. -/
@[specialize V] def log10 (t : Chain V G Float) : Multivector V Float := Multivector.log10 (toMultivector t)

end Chain

namespace Couple

/-- AbstractTensors `cot(t)` (`cos(t)/sin(t)`, `AT:410`) of a couple, on its multivector. -/
@[specialize V] def cot (t : Couple V Float) : Multivector V Float := Multivector.cot (toMultivector t)

/-- AbstractTensors `sec(t)` (`inv(cos(t))`, `AT:411`) of a couple, on its multivector. -/
@[specialize V] def sec (t : Couple V Float) : Multivector V Float := Multivector.sec (toMultivector t)

/-- AbstractTensors `csc(t)` (`inv(sin(t))`, `AT:412`) of a couple, on its multivector. -/
@[specialize V] def csc (t : Couple V Float) : Multivector V Float := Multivector.csc (toMultivector t)

/-- AbstractTensors `sech(t)` (`inv(cosh(t))`, `AT:415`) of a couple, on its multivector. -/
@[specialize V] def sech (t : Couple V Float) : Multivector V Float := Multivector.sech (toMultivector t)

/-- AbstractTensors `csch(t)` (`inv(sinh(t))`, `AT:416`) of a couple, on its multivector. -/
@[specialize V] def csch (t : Couple V Float) : Multivector V Float := Multivector.csch (toMultivector t)

/-- AbstractTensors `asin(t)` (`(-I) ⟑ log(I⟑t + sqrt(1 - t⟑t))`, `AT:425`) of a couple, on its multivector. -/
@[specialize V] def asin (t : Couple V Float) : Multivector V Float := Multivector.asin (toMultivector t)

/-- AbstractTensors `acos(t)` (`(-I) ⟑ log(t + I⟑sqrt(1 - t⟑t))`, `AT:426`) of a couple, on its multivector. -/
@[specialize V] def acos (t : Couple V Float) : Multivector V Float := Multivector.acos (toMultivector t)

/-- AbstractTensors `atan(t)` (`((-I)/2) ⟑ (log(1 + I⟑t) - log(1 - I⟑t))`, `AT:427`) of a couple, on its multivector. -/
@[specialize V] def atan (t : Couple V Float) : Multivector V Float := Multivector.atan (toMultivector t)

/-- AbstractTensors `acot(t)` (`((-I)/2) ⟑ (log(t - I) - log(t + I))`, `AT:428`) of a couple, on its multivector. -/
@[specialize V] def acot (t : Couple V Float) : Multivector V Float := Multivector.acot (toMultivector t)

/-- AbstractTensors `asec(t)` (`acos(inv(t))`, `AT:413`) of a couple, on its multivector. -/
@[specialize V] def asec (t : Couple V Float) : Multivector V Float := Multivector.asec (toMultivector t)

/-- AbstractTensors `acsc(t)` (`asin(inv(t))`, `AT:414`) of a couple, on its multivector. -/
@[specialize V] def acsc (t : Couple V Float) : Multivector V Float := Multivector.acsc (toMultivector t)

/-- AbstractTensors `asech(t)` (`acosh(inv(t))`, `AT:417`) of a couple, on its multivector. -/
@[specialize V] def asech (t : Couple V Float) : Multivector V Float := Multivector.asech (toMultivector t)

/-- AbstractTensors `acsch(t)` (`asinh(inv(t))`, `AT:418`) of a couple, on its multivector. -/
@[specialize V] def acsch (t : Couple V Float) : Multivector V Float := Multivector.acsch (toMultivector t)

/-- AbstractTensors `sinc(t)` (`sinc(t)`, `AT:429`) of a couple, on its multivector. -/
@[specialize V] def sinc (t : Couple V Float) : Multivector V Float := Multivector.sinc (toMultivector t)

/-- AbstractTensors `cosc(t)` (`cosc(t)`, `AT:430`) of a couple, on its multivector. -/
@[specialize V] def cosc (t : Couple V Float) : Multivector V Float := Multivector.cosc (toMultivector t)

end Couple

namespace PseudoCouple

/-- AbstractTensors `sqrt(t)` (`sqrt(t)`, `C:436-451`) of a pseudo-couple, on its multivector. -/
@[specialize V] def sqrt (t : PseudoCouple V Float) : Multivector V Float := Multivector.sqrt (toMultivector t)

/-- AbstractTensors `cbrt(t)` (`cbrt(t)`, `C:436-451`) of a pseudo-couple, on its multivector. -/
@[specialize V] def cbrt (t : PseudoCouple V Float) : Multivector V Float := Multivector.cbrt (toMultivector t)

/-- AbstractTensors `tanh(t)` (`sinh(t)/cosh(t)`, `AT:419`) of a pseudo-couple, on its multivector. -/
@[specialize V] def tanh (t : PseudoCouple V Float) : Multivector V Float := Multivector.tanh (toMultivector t)

/-- AbstractTensors `cot(t)` (`cos(t)/sin(t)`, `AT:410`) of a pseudo-couple, on its multivector. -/
@[specialize V] def cot (t : PseudoCouple V Float) : Multivector V Float := Multivector.cot (toMultivector t)

/-- AbstractTensors `sec(t)` (`inv(cos(t))`, `AT:411`) of a pseudo-couple, on its multivector. -/
@[specialize V] def sec (t : PseudoCouple V Float) : Multivector V Float := Multivector.sec (toMultivector t)

/-- AbstractTensors `csc(t)` (`inv(sin(t))`, `AT:412`) of a pseudo-couple, on its multivector. -/
@[specialize V] def csc (t : PseudoCouple V Float) : Multivector V Float := Multivector.csc (toMultivector t)

/-- AbstractTensors `coth(t)` (`cosh(t)/sinh(t)`, `AT:420`) of a pseudo-couple, on its multivector. -/
@[specialize V] def coth (t : PseudoCouple V Float) : Multivector V Float := Multivector.coth (toMultivector t)

/-- AbstractTensors `sech(t)` (`inv(cosh(t))`, `AT:415`) of a pseudo-couple, on its multivector. -/
@[specialize V] def sech (t : PseudoCouple V Float) : Multivector V Float := Multivector.sech (toMultivector t)

/-- AbstractTensors `csch(t)` (`inv(sinh(t))`, `AT:416`) of a pseudo-couple, on its multivector. -/
@[specialize V] def csch (t : PseudoCouple V Float) : Multivector V Float := Multivector.csch (toMultivector t)

/-- AbstractTensors `asin(t)` (`(-I) ⟑ log(I⟑t + sqrt(1 - t⟑t))`, `AT:425`) of a pseudo-couple, on its multivector. -/
@[specialize V] def asin (t : PseudoCouple V Float) : Multivector V Float := Multivector.asin (toMultivector t)

/-- AbstractTensors `acos(t)` (`(-I) ⟑ log(t + I⟑sqrt(1 - t⟑t))`, `AT:426`) of a pseudo-couple, on its multivector. -/
@[specialize V] def acos (t : PseudoCouple V Float) : Multivector V Float := Multivector.acos (toMultivector t)

/-- AbstractTensors `atan(t)` (`((-I)/2) ⟑ (log(1 + I⟑t) - log(1 - I⟑t))`, `AT:427`) of a pseudo-couple, on its multivector. -/
@[specialize V] def atan (t : PseudoCouple V Float) : Multivector V Float := Multivector.atan (toMultivector t)

/-- AbstractTensors `acot(t)` (`((-I)/2) ⟑ (log(t - I) - log(t + I))`, `AT:428`) of a pseudo-couple, on its multivector. -/
@[specialize V] def acot (t : PseudoCouple V Float) : Multivector V Float := Multivector.acot (toMultivector t)

/-- AbstractTensors `asec(t)` (`acos(inv(t))`, `AT:413`) of a pseudo-couple, on its multivector. -/
@[specialize V] def asec (t : PseudoCouple V Float) : Multivector V Float := Multivector.asec (toMultivector t)

/-- AbstractTensors `acsc(t)` (`asin(inv(t))`, `AT:414`) of a pseudo-couple, on its multivector. -/
@[specialize V] def acsc (t : PseudoCouple V Float) : Multivector V Float := Multivector.acsc (toMultivector t)

/-- AbstractTensors `asinh(t)` (`log(t + sqrt(1 + t⟑t))`, `AT:421`) of a pseudo-couple, on its multivector. -/
@[specialize V] def asinh (t : PseudoCouple V Float) : Multivector V Float := Multivector.asinh (toMultivector t)

/-- AbstractTensors `acosh(t)` (`log(t + sqrt(t⟑t - 1))`, `AT:422`) of a pseudo-couple, on its multivector. -/
@[specialize V] def acosh (t : PseudoCouple V Float) : Multivector V Float := Multivector.acosh (toMultivector t)

/-- AbstractTensors `atanh(t)` (`(log(1+t) - log(1-t))/2`, `AT:423`) of a pseudo-couple, on its multivector. -/
@[specialize V] def atanh (t : PseudoCouple V Float) : Multivector V Float := Multivector.atanh (toMultivector t)

/-- AbstractTensors `acoth(t)` (`(log(t+1) - log(t-1))/2`, `AT:424`) of a pseudo-couple, on its multivector. -/
@[specialize V] def acoth (t : PseudoCouple V Float) : Multivector V Float := Multivector.acoth (toMultivector t)

/-- AbstractTensors `asech(t)` (`acosh(inv(t))`, `AT:417`) of a pseudo-couple, on its multivector. -/
@[specialize V] def asech (t : PseudoCouple V Float) : Multivector V Float := Multivector.asech (toMultivector t)

/-- AbstractTensors `acsch(t)` (`asinh(inv(t))`, `AT:418`) of a pseudo-couple, on its multivector. -/
@[specialize V] def acsch (t : PseudoCouple V Float) : Multivector V Float := Multivector.acsch (toMultivector t)

/-- AbstractTensors `sinc(t)` (`sinc(t)`, `AT:429`) of a pseudo-couple, on its multivector. -/
@[specialize V] def sinc (t : PseudoCouple V Float) : Multivector V Float := Multivector.sinc (toMultivector t)

/-- AbstractTensors `cosc(t)` (`cosc(t)`, `AT:430`) of a pseudo-couple, on its multivector. -/
@[specialize V] def cosc (t : PseudoCouple V Float) : Multivector V Float := Multivector.cosc (toMultivector t)

/-- AbstractTensors `exp2(t)` (`exp(log(2)·t)`, `AT:384`) of a pseudo-couple, on its multivector. -/
@[specialize V] def exp2 (t : PseudoCouple V Float) : Multivector V Float := Multivector.exp2 (toMultivector t)

/-- AbstractTensors `exp10(t)` (`exp(log(10)·t)`, `AT:384`) of a pseudo-couple, on its multivector. -/
@[specialize V] def exp10 (t : PseudoCouple V Float) : Multivector V Float := Multivector.exp10 (toMultivector t)

/-- AbstractTensors `log2(t)` (`log2(ℯ)·log(t)`, `AT:383`) of a pseudo-couple, on its multivector. -/
@[specialize V] def log2 (t : PseudoCouple V Float) : Multivector V Float := Multivector.log2 (toMultivector t)

/-- AbstractTensors `log10(t)` (`log10(ℯ)·log(t)`, `AT:383`) of a pseudo-couple, on its multivector. -/
@[specialize V] def log10 (t : PseudoCouple V Float) : Multivector V Float := Multivector.log10 (toMultivector t)

end PseudoCouple

namespace Half

/-- AbstractTensors `cot(t)` (`cos(t)/sin(t)`, `AT:410`) of a spinor, on its multivector. -/
@[specialize V] def cot (t : Half V false Float) : Multivector V Float := Multivector.cot (toMultivector t)

/-- AbstractTensors `sec(t)` (`inv(cos(t))`, `AT:411`) of a spinor, on its multivector. -/
@[specialize V] def sec (t : Half V false Float) : Multivector V Float := Multivector.sec (toMultivector t)

/-- AbstractTensors `csc(t)` (`inv(sin(t))`, `AT:412`) of a spinor, on its multivector. -/
@[specialize V] def csc (t : Half V false Float) : Multivector V Float := Multivector.csc (toMultivector t)

/-- AbstractTensors `coth(t)` (`cosh(t)/sinh(t)`, `AT:420`) of a spinor, on its multivector. -/
@[specialize V] def coth (t : Half V false Float) : Multivector V Float := Multivector.coth (toMultivector t)

/-- AbstractTensors `sech(t)` (`inv(cosh(t))`, `AT:415`) of a spinor, on its multivector. -/
@[specialize V] def sech (t : Half V false Float) : Multivector V Float := Multivector.sech (toMultivector t)

/-- AbstractTensors `csch(t)` (`inv(sinh(t))`, `AT:416`) of a spinor, on its multivector. -/
@[specialize V] def csch (t : Half V false Float) : Multivector V Float := Multivector.csch (toMultivector t)

/-- AbstractTensors `asin(t)` (`(-I) ⟑ log(I⟑t + sqrt(1 - t⟑t))`, `AT:425`) of a spinor, on its multivector. -/
@[specialize V] def asin (t : Half V false Float) : Multivector V Float := Multivector.asin (toMultivector t)

/-- AbstractTensors `acos(t)` (`(-I) ⟑ log(t + I⟑sqrt(1 - t⟑t))`, `AT:426`) of a spinor, on its multivector. -/
@[specialize V] def acos (t : Half V false Float) : Multivector V Float := Multivector.acos (toMultivector t)

/-- AbstractTensors `atan(t)` (`((-I)/2) ⟑ (log(1 + I⟑t) - log(1 - I⟑t))`, `AT:427`) of a spinor, on its multivector. -/
@[specialize V] def atan (t : Half V false Float) : Multivector V Float := Multivector.atan (toMultivector t)

/-- AbstractTensors `acot(t)` (`((-I)/2) ⟑ (log(t - I) - log(t + I))`, `AT:428`) of a spinor, on its multivector. -/
@[specialize V] def acot (t : Half V false Float) : Multivector V Float := Multivector.acot (toMultivector t)

/-- AbstractTensors `asec(t)` (`acos(inv(t))`, `AT:413`) of a spinor, on its multivector. -/
@[specialize V] def asec (t : Half V false Float) : Multivector V Float := Multivector.asec (toMultivector t)

/-- AbstractTensors `acsc(t)` (`asin(inv(t))`, `AT:414`) of a spinor, on its multivector. -/
@[specialize V] def acsc (t : Half V false Float) : Multivector V Float := Multivector.acsc (toMultivector t)

/-- AbstractTensors `asech(t)` (`acosh(inv(t))`, `AT:417`) of a spinor, on its multivector. -/
@[specialize V] def asech (t : Half V false Float) : Multivector V Float := Multivector.asech (toMultivector t)

/-- AbstractTensors `acsch(t)` (`asinh(inv(t))`, `AT:418`) of a spinor, on its multivector. -/
@[specialize V] def acsch (t : Half V false Float) : Multivector V Float := Multivector.acsch (toMultivector t)

/-- AbstractTensors `sinc(t)` (`sinc(t)`, `AT:429`) of a spinor, on its multivector. -/
@[specialize V] def sinc (t : Half V false Float) : Multivector V Float := Multivector.sinc (toMultivector t)

/-- AbstractTensors `cosc(t)` (`cosc(t)`, `AT:430`) of a spinor, on its multivector. -/
@[specialize V] def cosc (t : Half V false Float) : Multivector V Float := Multivector.cosc (toMultivector t)

/-- AbstractTensors `exp2(t)` (`exp(log(2)·t)`, `AT:384`) of a spinor, on its multivector. -/
@[specialize V] def exp2 (t : Half V false Float) : Multivector V Float := Multivector.exp2 (toMultivector t)

/-- AbstractTensors `exp10(t)` (`exp(log(10)·t)`, `AT:384`) of a spinor, on its multivector. -/
@[specialize V] def exp10 (t : Half V false Float) : Multivector V Float := Multivector.exp10 (toMultivector t)

/-- AbstractTensors `log2(t)` (`log2(ℯ)·log(t)`, `AT:383`) of a spinor, on its multivector. -/
@[specialize V] def log2 (t : Half V false Float) : Multivector V Float := Multivector.log2 (toMultivector t)

/-- AbstractTensors `log10(t)` (`log10(ℯ)·log(t)`, `AT:383`) of a spinor, on its multivector. -/
@[specialize V] def log10 (t : Half V false Float) : Multivector V Float := Multivector.log10 (toMultivector t)

end Half

namespace CoSpinor

/-- AbstractTensors `tanh(t)` (`sinh(t)/cosh(t)`, `AT:419`) of a co-spinor, on its multivector. -/
@[specialize V] def tanh (t : CoSpinor V Float) : Multivector V Float := Multivector.tanh (toMultivector t)

/-- AbstractTensors `cot(t)` (`cos(t)/sin(t)`, `AT:410`) of a co-spinor, on its multivector. -/
@[specialize V] def cot (t : CoSpinor V Float) : Multivector V Float := Multivector.cot (toMultivector t)

/-- AbstractTensors `sec(t)` (`inv(cos(t))`, `AT:411`) of a co-spinor, on its multivector. -/
@[specialize V] def sec (t : CoSpinor V Float) : Multivector V Float := Multivector.sec (toMultivector t)

/-- AbstractTensors `csc(t)` (`inv(sin(t))`, `AT:412`) of a co-spinor, on its multivector. -/
@[specialize V] def csc (t : CoSpinor V Float) : Multivector V Float := Multivector.csc (toMultivector t)

/-- AbstractTensors `coth(t)` (`cosh(t)/sinh(t)`, `AT:420`) of a co-spinor, on its multivector. -/
@[specialize V] def coth (t : CoSpinor V Float) : Multivector V Float := Multivector.coth (toMultivector t)

/-- AbstractTensors `sech(t)` (`inv(cosh(t))`, `AT:415`) of a co-spinor, on its multivector. -/
@[specialize V] def sech (t : CoSpinor V Float) : Multivector V Float := Multivector.sech (toMultivector t)

/-- AbstractTensors `csch(t)` (`inv(sinh(t))`, `AT:416`) of a co-spinor, on its multivector. -/
@[specialize V] def csch (t : CoSpinor V Float) : Multivector V Float := Multivector.csch (toMultivector t)

/-- AbstractTensors `asin(t)` (`(-I) ⟑ log(I⟑t + sqrt(1 - t⟑t))`, `AT:425`) of a co-spinor, on its multivector. -/
@[specialize V] def asin (t : CoSpinor V Float) : Multivector V Float := Multivector.asin (toMultivector t)

/-- AbstractTensors `acos(t)` (`(-I) ⟑ log(t + I⟑sqrt(1 - t⟑t))`, `AT:426`) of a co-spinor, on its multivector. -/
@[specialize V] def acos (t : CoSpinor V Float) : Multivector V Float := Multivector.acos (toMultivector t)

/-- AbstractTensors `atan(t)` (`((-I)/2) ⟑ (log(1 + I⟑t) - log(1 - I⟑t))`, `AT:427`) of a co-spinor, on its multivector. -/
@[specialize V] def atan (t : CoSpinor V Float) : Multivector V Float := Multivector.atan (toMultivector t)

/-- AbstractTensors `acot(t)` (`((-I)/2) ⟑ (log(t - I) - log(t + I))`, `AT:428`) of a co-spinor, on its multivector. -/
@[specialize V] def acot (t : CoSpinor V Float) : Multivector V Float := Multivector.acot (toMultivector t)

/-- AbstractTensors `asec(t)` (`acos(inv(t))`, `AT:413`) of a co-spinor, on its multivector. -/
@[specialize V] def asec (t : CoSpinor V Float) : Multivector V Float := Multivector.asec (toMultivector t)

/-- AbstractTensors `acsc(t)` (`asin(inv(t))`, `AT:414`) of a co-spinor, on its multivector. -/
@[specialize V] def acsc (t : CoSpinor V Float) : Multivector V Float := Multivector.acsc (toMultivector t)

/-- AbstractTensors `asinh(t)` (`log(t + sqrt(1 + t⟑t))`, `AT:421`) of a co-spinor, on its multivector. -/
@[specialize V] def asinh (t : CoSpinor V Float) : Multivector V Float := Multivector.asinh (toMultivector t)

/-- AbstractTensors `acosh(t)` (`log(t + sqrt(t⟑t - 1))`, `AT:422`) of a co-spinor, on its multivector. -/
@[specialize V] def acosh (t : CoSpinor V Float) : Multivector V Float := Multivector.acosh (toMultivector t)

/-- AbstractTensors `atanh(t)` (`(log(1+t) - log(1-t))/2`, `AT:423`) of a co-spinor, on its multivector. -/
@[specialize V] def atanh (t : CoSpinor V Float) : Multivector V Float := Multivector.atanh (toMultivector t)

/-- AbstractTensors `acoth(t)` (`(log(t+1) - log(t-1))/2`, `AT:424`) of a co-spinor, on its multivector. -/
@[specialize V] def acoth (t : CoSpinor V Float) : Multivector V Float := Multivector.acoth (toMultivector t)

/-- AbstractTensors `asech(t)` (`acosh(inv(t))`, `AT:417`) of a co-spinor, on its multivector. -/
@[specialize V] def asech (t : CoSpinor V Float) : Multivector V Float := Multivector.asech (toMultivector t)

/-- AbstractTensors `acsch(t)` (`asinh(inv(t))`, `AT:418`) of a co-spinor, on its multivector. -/
@[specialize V] def acsch (t : CoSpinor V Float) : Multivector V Float := Multivector.acsch (toMultivector t)

/-- AbstractTensors `sinc(t)` (`sinc(t)`, `AT:429`) of a co-spinor, on its multivector. -/
@[specialize V] def sinc (t : CoSpinor V Float) : Multivector V Float := Multivector.sinc (toMultivector t)

/-- AbstractTensors `cosc(t)` (`cosc(t)`, `AT:430`) of a co-spinor, on its multivector. -/
@[specialize V] def cosc (t : CoSpinor V Float) : Multivector V Float := Multivector.cosc (toMultivector t)

/-- AbstractTensors `exp2(t)` (`exp(log(2)·t)`, `AT:384`) of a co-spinor, on its multivector. -/
@[specialize V] def exp2 (t : CoSpinor V Float) : Multivector V Float := Multivector.exp2 (toMultivector t)

/-- AbstractTensors `exp10(t)` (`exp(log(10)·t)`, `AT:384`) of a co-spinor, on its multivector. -/
@[specialize V] def exp10 (t : CoSpinor V Float) : Multivector V Float := Multivector.exp10 (toMultivector t)

/-- AbstractTensors `log2(t)` (`log2(ℯ)·log(t)`, `AT:383`) of a co-spinor, on its multivector. -/
@[specialize V] def log2 (t : CoSpinor V Float) : Multivector V Float := Multivector.log2 (toMultivector t)

/-- AbstractTensors `log10(t)` (`log10(ℯ)·log(t)`, `AT:383`) of a co-spinor, on its multivector. -/
@[specialize V] def log10 (t : CoSpinor V Float) : Multivector V Float := Multivector.log10 (toMultivector t)

end CoSpinor

namespace Phasor

/-- Julia `sin(z::Phasor)`: `sin(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def sin (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.sin z.complexify)

/-- Julia `cos(z::Phasor)`: `cos(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def cos (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.cos z.complexify)

/-- Julia `tan(z::Phasor)`: `tan(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def tan (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.tan z.complexify)

/-- Julia `sinh(z::Phasor)`: `sinh(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def sinh (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.sinh z.complexify)

/-- Julia `cosh(z::Phasor)`: `cosh(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def cosh (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.cosh z.complexify)

/-- Julia `tanh(z::Phasor)`: `tanh(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def tanh (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.tanh z.complexify)

/-- Julia `cot(z::Phasor)`: `cot(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def cot (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.cot z.complexify)

/-- Julia `sec(z::Phasor)`: `sec(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def sec (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.sec z.complexify)

/-- Julia `csc(z::Phasor)`: `csc(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def csc (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.csc z.complexify)

/-- Julia `coth(z::Phasor)`: `coth(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def coth (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.coth z.complexify)

/-- Julia `sech(z::Phasor)`: `sech(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def sech (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.sech z.complexify)

/-- Julia `csch(z::Phasor)`: `csch(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def csch (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.csch z.complexify)

/-- Julia `asin(z::Phasor)`: `asin(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def asin (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.asin z.complexify)

/-- Julia `acos(z::Phasor)`: `acos(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def acos (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.acos z.complexify)

/-- Julia `atan(z::Phasor)`: `atan(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def atan (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.atan z.complexify)

/-- Julia `acot(z::Phasor)`: `acot(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def acot (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.acot z.complexify)

/-- Julia `asinh(z::Phasor)`: `asinh(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def asinh (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.asinh z.complexify)

/-- Julia `acosh(z::Phasor)`: `acosh(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def acosh (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.acosh z.complexify)

/-- Julia `atanh(z::Phasor)`: `atanh(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def atanh (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.atanh z.complexify)

/-- Julia `acoth(z::Phasor)`: `acoth(complexify(z))` (a phasor is a couple in polar form). -/
@[specialize V] def acoth (z : Phasor V Float) : Multivector V Float := toMultivector (Couple.acoth z.complexify)

end Phasor

end Grassmann
