/-
The `Λ` basis container: `Tests/DirectSum/golden/basis.json` (generated by
`Tests/DirectSum/golden/gen_basis.jl`) for `Λ(V)[i]`, `Λ(n,d,o,s)`, `Λ"…"`,
`Λ(V)'` and `Λ(V) ⊕ Λ(W)`, plus the `Λ(V).name` syntax on the DirectSum README
examples at compile time (a signed or scaled name is a `Grassmann.Single`).

Documented Julia defects skipped and counted:

* `Λ"∞∅+++"` (`Basis(str)`) misreads a conformal signature string (it prints a
  3-dimensional `⟨++,∞∅,+⟩`); the port's `Λ!"∞∅+++"` is the basis of
  `S!"∞∅+++"`;
* `Λ(V).v11` and `Λ(D"1,2,3").v33` ignore the metric of a repeated generator
  (quirk Q16, as in the `spaces` suite); the port applies it.
-/
import Tests.DirectSum.Common
import Tests.DirectSum.Spaces
import DirectSum.Basis
import Grassmann

open Lean DirectSum DirectSum.Bits

namespace DirectSumTests.BasisSuite

/-! ## The `Λ(V).name` syntax (DirectSum README:179-183, test lines 11 and 13) -/

example : Λ(3).v12.indices = [1, 2] := by decide
#guard (Λ(62).v32a87Ng == (-1 : Int) * Λ(62).v2378agN)
#guard toString Λ(3).v21 == "-1v₁₂"
#guard toString (Λ(3)[5]) == "v₁₂"
#guard toString Λ(62).v2378agN == "v₂₃₇₈agN"
#guard toString Λ(62).v32a87Ng == "-1v₂₃₇₈agN"
#guard toString Λ(ℝ^3).v312 == "v₁₂₃"
#guard toString Λ(S!"∞∅+").«v∞∅1» == "v∞∅₁"
#guard toString Λ(ℝ^3).v == "v"
example : Λ(ℝ^3).v12 = (⟨3⟩ : Submanifold (ℝ^3) 2) := rfl
#guard toString Λ!"-+++" == "DirectSum.Basis{⟨-+++⟩,16}(v, v₁, v₂, v₃, v₄, v₁₂, v₁₃, v₁₄, v₂₃, v₂₄, v₃₄, v₁₂₃, v₁₂₄, v₁₃₄, v₂₃₄, v₁₂₃₄)"
#guard toString (Λ(ℝ^14).oplus Λ(ℝ^14).dual) ==
  "DirectSum.ExtendedBasis{⟨++++++++++++++--------------⟩*,268435456}(v, ..., v₁₂₃₄₅₆₇₈₉₀abcdw¹²³⁴⁵⁶⁷⁸⁹⁰ABCD)"

/-! ## Oracle records -/

/-- Check `basis.json`. -/
def check (root : Json) : Tally := Id.run do
  let mut t : Tally := {}
  for r in (root.getObjValD "getindex").getArr?.toOption.getD #[] do
    match Spaces.build (r.getObjValD "space") with
    | .error e => t := t.bad s!"getindex recipe: {e}"
    | .ok V =>
      let L := Λ V
      t := t.check (toString L == jStr r "show") s!"Λ({V}) show: {L}"
      let items := (jArr r "items").map fun j => j.getStr?.toOption.getD ""
      let got := (List.range (2 ^ V.n)).toArray.map fun i => toString (L.get (i + 1))
      t := t.check (got == items) s!"Λ({V})[i]: {got}"
  for r in (root.getObjValD "codes").getArr?.toOption.getD #[] do
    let V := TensorBundle.ofCode (jNat r "n") (jNat r "d" != 0) (jNat r "o" != 0) (jNat r "s").toUInt64
    t := t.check (toString (Λ V) == jStr r "show") s!"Λ(n,d,o,s) {r.compress}: {Λ V}"
  for r in (root.getObjValD "strs").getArr?.toOption.getD #[] do
    let s := jStr r "s"
    if (s.splitOn "∞").length > 1 then t := t.defect "Basis(str) misreads conformal strings"
    else
      match TensorBundle.parseBundle s with
      | .error e => t := t.bad s!"Λ\"{s}\": {e}"
      | .ok V => t := t.check (toString (Λ V) == jStr r "show") s!"Λ\"{s}\": {Λ V}"
  for r in (root.getObjValD "sums").getArr?.toOption.getD #[] do
    match Spaces.build (r.getObjValD "a"), Spaces.build (r.getObjValD "b") with
    | .ok A, .ok B =>
      let S := (Λ A).oplus (Λ B)
      t := t.check (toString S == jStr r "show") s!"Λ({A}) ⊕ Λ({B}): {S}"
    | _, _ => t := t.bad "sum recipe"
  for r in (root.getObjValD "duals").getArr?.toOption.getD #[] do
    match Spaces.build (r.getObjValD "space") with
    | .ok V => t := t.check (toString (Λ V).dual == jStr r "show") s!"Λ({V})': {(Λ V).dual}"
    | .error e => t := t.bad e
  -- the README names, looked up at run time (the syntax is checked above)
  let readme := root.getObjValD "readme"
  let str := fun (k : String) => (readme.getObjValD k).getStr?.toOption.getD ""
  let showR := fun (V : TensorBundle) (r : Option BladeResult) => match r with
    | some (.blade b) => V.bladeLabel b
    | some (.single c b) => V.showTerm c b
    | _ => "?"
  let E3 := TensorBundle.euclidean 3
  let E62 := TensorBundle.euclidean 62
  t := t.check (showR E3 (E3.lookup "v21") == str "Λ(3).v21") "Λ(3).v21"
  t := t.check (showR E62 (E62.lookup "v32a87Ng") == str "Λ(62).v32a87Ng") "Λ(62).v32a87Ng"
  t := t.check (showR (ℝ^3) ((ℝ^3).lookup "v312") == str "Λ(ℝ^3).v312") "Λ(ℝ^3).v312"
  t := t.check (toString ((Λ E3)[5]'(by decide)) == str "Λ(3)[5]") "Λ(3)[5]"
  -- Julia drops the metric of a repeated generator (Q16): `Λ(S"-+++").v11 = v`, `Λ(D"1,2,3").v33 = v`
  t := t.defect "Q16 repeated-index metric through Λ(V)"
  t := t.defect "Q16 repeated-index metric through Λ(V)"
  return t

/-- Run the suite. -/
def run : IO Tally := do
  match Json.parse (← IO.FS.readFile "Tests/DirectSum/golden/basis.json") with
  | .error e => return ({} : Tally).bad s!"basis.json: {e}"
  | .ok root => return check root

end DirectSumTests.BasisSuite
