/-
Leibniz additions against `Tests/DirectSum/golden/leibniz.json` (generated by
`Tests/DirectSum/golden/gen_leibniz.jl`): `Derivation` display and arithmetic (`∇^O`,
`(-∇)^O`, scalar products and quotients, `∇^2 == Δ`), `gdimseven`/`gdimsodd`, `indexsplit`,
and per blade `order`, `isinf`, `isorigin`, `symmetricsplit`, `χ`, `count_gdims`, `≅`, plus
`count_gdims`/`χ` of chains.

Documented Julia defects skipped and counted: `∇ + ∇`, `Δ + Δ` throw `InexactError: Bool(2)`
(Leibniz quirk Q7; the port gives `2∂ₖvₖ`); `∇ + 1` has no method; orders past 36 have no
superscript (`KeyError`; the port prints `?`); `gdimsodd(0)` throws (the port: `[]`);
`isorigin` of a non-origin single-generator blade is `true` (the port tests the `∅` bit).
-/
import Tests.DirectSum.Common
import Tests.DirectSum.Spaces
import Leibniz.Derivation
import DirectSum.Euler

open Lean DirectSum DirectSum.Bits Leibniz

namespace DirectSumTests.LeibnizSuite

/-- The Lean value of each arithmetic expression of the golden. -/
def arith : List (String × String) :=
  [ ("-nabla", toString (-nabla)), ("-Delta", toString (-Δ)),
    ("2*nabla", toString ((2 : Int) * nabla)), ("nabla*3", toString (nabla * (3 : Int))),
    ("2.5*nabla", toString ((2.5 : Float) * nabla)), ("nabla/2", toString (nabla / (2 : Int))),
    ("2\\nabla", toString (Derivation.ldiv 2 nabla)),
    ("(2*nabla)+(3*nabla)", toString ((2 : Int) * nabla + (3 : Int) * nabla)),
    ("(2*nabla)-(3*nabla)", toString ((2 : Int) * nabla - (3 : Int) * nabla)),
    ("(2*nabla)*(3*nabla)", toString (((2 : Int) * nabla) * ((3 : Int) * nabla))),
    ("(2*Delta)^2", toString (((2 : Int) * Δ) ^ 2)), ("(2*nabla)^3", toString (((2 : Int) * nabla) ^ 3)),
    ("(-2*nabla)^3", toString (((-2 : Int) * nabla) ^ 3)), ("-(2*nabla)", toString (-((2 : Int) * nabla))),
    ("(4*nabla)/(2*nabla)", toString (((4 : Int) * nabla) / ((2 : Int) * nabla))),
    ("nabla+nabla", toString (nabla + nabla)), ("Delta+Delta", toString (Δ + Δ)),
    ("nabla+1", "∇ + 1 is not defined"), ("nabla^37", toString (nabla ^ 37)),
    ("nabla^2==Delta", toString (nabla ^ 2 == Δ)), ("(-nabla)^2==Delta", toString ((-nabla) ^ 2 == Δ)),
    ("nabla==nabla", toString (nabla == nabla)), ("(-nabla)==nabla", toString ((-nabla) == nabla)) ]

/-- A golden field printed like Julia (`true`, `3`, `"[1, 2]"`). -/
def jshow (j : Json) : String :=
  match j with
  | .bool b => toString b
  | .num n => toString (jsonRat n).num
  | .str s => s
  | _ => "?"

/-- Julia's display of a `Vector{Int}`. -/
def showArr (a : Array Nat) : String := "[" ++ ", ".intercalate (a.toList.map toString) ++ "]"

/-- A JSON array of naturals. -/
def natArr (j : Json) (k : String) : Array Nat :=
  (jArr j k).map fun x => match x with | .num v => (jsonRat v).num.toNat | _ => 0

/-- Check the golden. -/
def check (root : Json) : Tally := Id.run do
  let mut t : Tally := {}
  for r in jArr root "derivation" do
    let e := jStr r "expr"
    let want := jshow (r.getObjValD "show")
    let got? : Option String := match r.getObjValD "pow" with
      | .num p =>
        let o := (jsonRat p).num.toNat
        some (if jInt r "sign" == 1 then toString (nabla ^ o) else toString ((-nabla) ^ o))
      | _ => arith.lookup e
    match got? with
    | none => t := t.bad s!"derivation {e}: no Lean expression"
    | some got =>
      if want.startsWith "error:" then
        t := t.defect (if (want.splitOn "InexactError").length > 1 then "Q7 Bool derivation sums"
          else if (want.splitOn "KeyError").length > 1 then "no superscript past 36"
          else "∇ + number has no method")
      else t := t.check (got == want) s!"derivation {e}: {got} vs {want}"
  for r in jArr root "gdims" do
    let n := jNat r "n"
    t := t.check (showArr (gdimseven n) == jStr r "even") s!"gdimseven {n}"
    let odd := jStr r "odd"
    if odd.startsWith "error:" then t := t.defect "gdimsodd(0) throws"
    else t := t.check (showArr (gdimsodd n) == odd) s!"gdimsodd {n}"
  for r in jArr root "indexsplit" do
    let got := (indexsplit (jNat r "b").toUInt64).map (·.toNat)
    t := t.check (got == natArr r "out") s!"indexsplit {jNat r "b"}"
  for r in jArr root "blades" do
    match Spaces.build (r.getObjValD "space") with
    | .error e => t := t.bad e
    | .ok V =>
      let b := (jNat r "b").toUInt64
      let lbl := s!"{V} {b}"
      t := t.check (toString (V.orderOf b) == jshow (r.getObjValD "order")) s!"order {lbl}"
      t := t.check (toString (V.isinfBlade b) == jshow (r.getObjValD "isinf")) s!"isinf {lbl}"
      let io := jshow (r.getObjValD "isorigin")
      if toString (V.isoriginBlade b) == io then t := t.ok
      else if io == "true" && popcount b == 1 then t := t.defect "isorigin of any single generator"
      else t := t.bad s!"isorigin {lbl}"
      let (s1, s2) := V.symmetricsplit b
      let ss := if V.isdyadic then s!"[{s1}, {s2}]" else s!"[{s1}]"
      t := t.check (ss == jshow (r.getObjValD "symsplit")) s!"symmetricsplit {lbl}: {ss}"
      t := t.check (toString (V.chiBlade b) == jshow (r.getObjValD "chi")) s!"chi {lbl}"
      t := t.check (showArr (V.countGdims #[b]) == jshow (r.getObjValD "count_gdims"))
        s!"count_gdims {lbl}"
  for r in jArr root "same" do
    match Spaces.build (r.getObjValD "space") with
    | .error e => t := t.bad e
    | .ok V =>
      let got := V.sameKind (jNat r "a").toUInt64 (jNat r "b").toUInt64
      t := t.check (toString got == jshow (r.getObjValD "out")) s!"≅ {jNat r "a"} {jNat r "b"}"
  for r in jArr root "chains" do
    match Spaces.build (r.getObjValD "space") with
    | .error e => t := t.bad e
    | .ok V =>
      let g := jNat r "G"
      let cs := natArr r "coeffs"
      let masks := (Leibniz.indexBasis V.n g).zipIdx.filterMap fun (m, i) =>
        if cs[i]?.getD 0 != 0 then some m else none
      let counts := V.countGdims masks
      t := t.check (showArr counts == jshow (r.getObjValD "count_gdims")) s!"chain count_gdims {V} {g} {cs}"
      t := t.check (toString (eulerChar counts) == jshow (r.getObjValD "chi")) s!"chain chi {V} {g} {cs}"
  return t

/-- Run the suite. -/
def run : IO Tally := do
  match Json.parse (← IO.FS.readFile "Tests/DirectSum/golden/leibniz.json") with
  | .error e => return ({} : Tally).bad s!"leibniz.json: {e}"
  | .ok root => return check root

end DirectSumTests.LeibnizSuite
