/-
Set-theory oracle suite: `Tests/DirectSum/golden/setops.json` (generated by
`Tests/DirectSum/golden/gen_setops.jl`). Every pair of spaces, subspaces and
basis blades is rebuilt from its recipe and compared on `∪`, `∩`, `⊆`, `==`
and `⊕` (printed result, Boolean, or "Julia throws"), then the `+`, `^`,
variadic folds, `subtangent` and subspace metric/basis records.

Documented Julia defects that the port fixes are skipped and counted:

* `DiagnoalForm` typo (`operations.jl:104,131`): `∪`/`∩` of diagonal forms that
  differ in their tangent variables throw `UndefVarError`;
* `Int` handles (`ℝ3 = Submanifold(3)`) against `DiagonalForm`s fail Julia's type
  promotion, and two handles of different sizes overflow the stack; the port
  compares an `Int` space as the `Signature` it stands for;
* subspaces of unrelated spaces recurse through `interop` until the stack
  overflows (the generator records these without running them);
* Julia's dispatch compares the metric parameter `S` of a `DiagonalForm` (an
  index into its value cache) with a `Signature`'s metric bits, so where the
  two happen to coincide it treats the spaces as having the same metric
  (`S"-++" ∪ tangent(D"1,2,3") = T¹⟨-++₁⟩`); the port never mixes the families;
* `ℝ3 ⊆ ℝ4` (and subspaces of `ℝ3` in `ℝ^4`) reach `Base.issubset` on integers
  (`false`); the port compares `Int` spaces as `Signature`s (`true`);
* `⊕` of two subspaces of one tangent space builds a non-dyadic tangent sum in
  Julia (quirk Q9), which `TensorBundle.oplus` rejects.
-/
import Tests.DirectSum.Common
import Tests.DirectSum.Spaces
import DirectSum.SetOps

open Lean DirectSum DirectSum.Bits

namespace DirectSumTests.SetOps

/-- A Julia manifold value: a space, a subspace of a space, or a basis blade. -/
inductive Item where
  | bundle (V : TensorBundle)
  | sub (V : TensorBundle) (s : SubSpace V)
  | blade (V : TensorBundle) (b : UInt64)

/-- Rebuild an item from its recipe. -/
def build (spec : Json) : Except String Item := do
  match jStr spec "op" with
  | "sub" =>
    let V ← Spaces.build (spec.getObjValD "of")
    let idx := (jArr spec "idx").toList.map fun j => match j with
      | .num n => (jsonRat n).num.toNat | _ => 0
    return .sub V (V.sub idx)
  | "blade" =>
    let V ← Spaces.build (spec.getObjValD "of")
    return .blade V (jNat spec "bits").toUInt64
  | _ => return .bundle (← Spaces.build spec)

/-- Whether a recipe mentions an `Int` space or a `DiagonalForm`. -/
partial def mentions (op : String) (spec : Json) : Bool :=
  jStr spec "op" == op || ["of", "a", "b"].any fun k =>
    match spec.getObjValD k with
    | .obj _ => mentions op (spec.getObjValD k)
    | _ => false

/-- A result as the golden records it: a printed value, a Boolean, or an error. -/
inductive Res where
  | str (s : String)
  | bool (b : Bool)
  | err (e : String)

/-- Lift a Lean result. -/
def ofExcept {α : Type} (f : α → Res) : Except String α → Res
  | .ok x => f x
  | .error e => .err e

/-- Decode the golden field. -/
def ofJson (j : Json) : Res :=
  match j with
  | .bool b => .bool b
  | .str s => if s.startsWith "error:" then .err s else .str s
  | _ => .err "missing"

/-- Compare a Lean result with the golden one: equal strings or Booleans, or both errors. -/
def agree : Res → Res → Bool
  | .str a, .str b => a == b
  | .bool a, .bool b => a == b
  | .err _, .err _ => true
  | _, _ => false

/-- Display for failure messages. -/
def Res.show : Res → String
  | .str s => s
  | .bool b => toString b
  | .err e => "<" ++ e ++ ">"

/-- The Lean side of one operation on a pair of items (`none`: not applicable). -/
def leanOp (kind op : String) (a b : Item) : Option Res :=
  let sBool := fun (r : Except String Bool) => ofExcept Res.bool r
  let sSpace := fun (r : Except String TensorBundle) => ofExcept (fun V => Res.str (toString V)) r
  match kind, op, a, b with
  -- spaces
  | "bundle", "union", .bundle A, .bundle B => some (sSpace (A.union B))
  | "bundle", "inter", .bundle A, .bundle B => some (sSpace (A.inter B))
  | "bundle", "subset", .bundle A, .bundle B => some (sBool (A.subset? B))
  | "bundle", "equal", .bundle A, .bundle B => some (sBool (A.equal? B))
  -- subspaces
  | "sub", "union", .sub _ x, .sub _ y => some (ofExcept (fun u => .str (toString u)) (x.unionAny y))
  | "sub", "inter", .sub V x, .sub W y =>
    some (if V == W then .str (toString (x ∩ (⟨y.mask⟩ : SubSpace V))) else .err "different spaces")
  | "sub", "subset", .sub _ x, .sub _ y => some (sBool (x.subsetAny y))
  | "sub", "oplus", .sub _ x, .sub _ y => some (ofExcept (fun u => .str (toString u)) (x.oplus y))
  | "subbundle", "union", .sub _ x, .bundle B => some (sSpace (x.unionBundle B))
  | "subbundle", "subset", .sub _ x, .bundle B => some (sBool (SubsetOf.subset? x B))
  | "bundlesub", "union", .bundle B, .sub _ x => some (sSpace (SubSpace.bundleUnion B x))
  | "bundlesub", "inter", .bundle B, .sub _ x =>
    some (ofExcept (fun o => .str (match o with | some s => toString s | none => "⟨⟩")) (x.interBundle B))
  | "bundlesub", "subset", .bundle B, .sub _ x => some (sBool (SubsetOf.subset? B x))
  -- blades (of one space)
  | "blade", "union", .blade V x, .blade _ y =>
    some (.str (toString (Submanifold.union (G := popcount x) (H := popcount y) (V := V) ⟨x⟩ ⟨y⟩)))
  | "blade", "inter", .blade V x, .blade _ y =>
    some (.str (toString (Submanifold.inter (G := popcount x) (H := popcount y) (V := V) ⟨x⟩ ⟨y⟩)))
  | "blade", "subset", .blade V x, .blade _ y =>
    some (sBool (SubsetOf.subset? (⟨x⟩ : Submanifold V (popcount x)) (⟨y⟩ : Submanifold V (popcount y))))
  | "bladebundle", "subset", .blade V x, .bundle B =>
    some (sBool (SubsetOf.subset? (⟨x⟩ : Submanifold V (popcount x)) B))
  | "bundleblade", "union", .bundle B, .blade V _ => some (sSpace (B.union V))
  | "bundleblade", "inter", .bundle B, .blade V x =>
    some (ofExcept (fun o => .str (match o with | some s => toString s | none => "⟨⟩"))
      (Submanifold.interBundle (⟨x⟩ : Submanifold V (popcount x)) B))
  | "bundleblade", "subset", .bundle B, .blade V x =>
    some (sBool (SubsetOf.subset? B (⟨x⟩ : Submanifold V (popcount x))))
  | _, _, _, _ => none

/-- The documented defect class of a golden error, if any. -/
def defectOf (a b : Json) (msg : String) : Option String :=
  if (msg.splitOn "DiagnoalForm").length > 1 then some "DiagnoalForm typo (operations.jl:104,131)"
  else if (msg.splitOn "StackOverflowError").length > 1 then some "stack overflow (Int handles / interop)"
  else if (mentions "I" a || mentions "I" b) && (msg.splitOn "promotion of types").length > 1 then
    some "Int handle vs DiagonalForm promotion"
  else none

/-- Check every pair record. -/
def checkCases (t : Tally) (cases : Array Json) : Tally := Id.run do
  let mut t := t
  for c in cases do
    let kind := jStr c "kind"
    let sa := c.getObjValD "a"
    let sb := c.getObjValD "b"
    match build sa, build sb with
    | .ok a, .ok b =>
      for op in ["union", "inter", "subset", "equal", "oplus"] do
        match c.getObjValD op with
        | .null => pure ()
        | j =>
          let want := ofJson j
          match leanOp kind op a b with
          | none => t := t.bad s!"{kind}/{op}: no Lean operation"
          | some got =>
            let msg := s!"{kind} {op} {sa.compress} {sb.compress}: {got.show} vs {want.show}"
            let cls := match want with
              | .err e => defectOf sa sb e
              | _ => none
            -- Julia compares a `DiagonalForm`'s cache index with a `Signature`'s metric bits as
            -- the same type parameter `S`: where they coincide it mixes the two families.
            let cls := if cls.isNone && !agree got want && mentions "D" sa != mentions "D" sb then
                some "DiagonalForm cache index taken for Signature bits" else cls
            -- `ℝ3 ⊆ ℝ4`, `ℝ3(1,2) ⊆ ℝ^4`: Julia reaches `Base.issubset(3, ·)` on an integer.
            let cls := if cls.isNone && op == "subset" && (mentions "I" sa || mentions "I" sb) &&
                agree got (.bool true) && agree want (.bool false) then
                some "Int handle compared by Base.issubset" else cls
            -- `⊕` of two subspaces of one tangent space: Julia builds a non-dyadic tangent sum
            -- (quirk Q9), which the port rejects.
            let cls := if cls.isNone && op == "oplus" && mentions "tangent" sa && !agree got want then
                some "non-dyadic tangent direct sum (quirk Q9)" else cls
            match cls with
            | some cls => t := t.defect cls
            | none => t := t.check (agree got want) msg
    | _, _ => t := t.bad s!"recipe failed: {sa.compress} / {sb.compress}"
  return t

/-- Check the `+`, `^`, fold, `subtangent` and subspace records. -/
def checkMisc (t : Tally) (misc : Array Json) : Tally := Id.run do
  let mut t := t
  let space := fun (j : Json) => Spaces.build j
  let showS := fun (r : Except String TensorBundle) => ofExcept (fun V => Res.str (toString V)) r
  for m in misc do
    let want := ofJson (m.getObjValD "out")
    let got : Except String Res := do
      match jStr m "op" with
      | "plus" =>
        let A ← space (m.getObjValD "a")
        let B ← space (m.getObjValD "b")
        return showS (A.oplus B)
      | "pow" => return showS ((← space (m.getObjValD "a")).pow (jNat m "i"))
      | "unionall" | "interall" =>
        let xs ← (jArr m "xs").toList.mapM space
        match xs with
        | x :: rest =>
          return showS (if jStr m "op" == "unionall" then x.unionAll rest else x.interAll rest)
        | [] => throw "empty"
      | "subtangent" => return .str (toString (← space (m.getObjValD "a")).subtangent)
      | "subinfo" =>
        match ← build (m.getObjValD "a") with
        | .sub _ s =>
          let ms := (jArr m "metrics").toList.map fun j => j.getStr?.toOption.getD ""
          -- Julia's `M[:]` of a subspace of an `Int` space lists the whole space's metric.
          let ok := s.mdims == jNat m "mdims" && s.diffvars == jNat m "diffvars" &&
            (mentions "I" (m.getObjValD "a") || s.metricList.map showDiagEntry == ms)
          return .str (if ok then s.showBasis else s!"mdims {s.mdims} diffvars {s.diffvars}")
        | _ => throw "not a subspace"
      | op => throw s!"unknown misc op {op}"
    let want := if jStr m "op" == "subinfo" then ofJson (m.getObjValD "collect") else want
    match got with
    | .ok g => t := t.check (agree g want) s!"misc {m.compress}: {g.show}"
    | .error e => t := t.bad s!"misc {m.compress}: {e}"
  return t

/-- Run the suite. -/
def run : IO Tally := do
  let j ← IO.FS.readFile "Tests/DirectSum/golden/setops.json"
  match Json.parse j with
  | .error e => return ({} : Tally).bad s!"setops.json: {e}"
  | .ok root =>
    let t := checkCases {} (root.getObjValD "cases").getArr?.toOption.get!
    return checkMisc t (root.getObjValD "misc").getArr?.toOption.get!

end DirectSumTests.SetOps
