/-
Space, index-table and printing oracle suite: `Tests/DirectSum/golden/spaces.json`
(generated by `Tests/DirectSum/golden/gen_spaces.jl` from DirectSum 0.8.21 /
Leibniz 0.3). Every space is rebuilt from its JSON recipe with the Lean API and
compared on parameters, bare/handle/subspace display, adjoint/dual, labels and
blade names; then string grammars, index tables, index glyphs, complement
masks and grade parities.

Documented Julia quirks that are *fixed* rather than replicated are skipped
and counted (Leibniz Q2: cumulative sums and `antiindex` for `n < 2`).
-/
import Tests.DirectSum.Common
import DirectSum.Compat
import DirectSum.Names

open Lean DirectSum DirectSum.Bits

namespace DirectSumTests.Spaces

/-- Rebuild a space from its JSON recipe (`gen_spaces.jl`). -/
partial def build (spec : Json) : Except String TensorBundle := do
  match jStr spec "op" with
  | "S" => TensorBundle.parseSignature (jStr spec "s")
  | "D" => return TensorBundle.diag ((jArr spec "vals").map fun | .num x => jsonRat x | _ => 0)
  | "I" => return TensorBundle.euclidean (jNat spec "n")
  | "R" => return TensorBundle.sig (jNat spec "n")
  | "adjoint" => (← build (spec.getObjValD "of")).adjoint
  | "tangent" =>
    let V ← build (spec.getObjValD "of")
    match spec.getObjValD "nu" with
    | .num nu => return V.tangent (jNat spec "mu") (jsonRat nu).num.toNat
    | _ => return V.tangent (jNat spec "mu")
  | "oplus" => TensorBundle.oplus (← build (spec.getObjValD "a")) (← build (spec.getObjValD "b"))
  | "raw" =>
    let m := jNat spec "opts"
    return { n := jNat spec "n", metric := .signature (jNat spec "metric").toUInt64,
             hasinf := m % 2 == 1, hasorigin := (m / 2) % 2 == 1,
             dyadmode := if (m / 8) % 2 == 1 then -1 else if (m / 4) % 2 == 1 then 1 else 0,
             polymode := (m / 16) % 2 == 0, diffvars := jNat spec "F", diffmode := jNat spec "D",
             name := jNat spec "L" }
  | op => throw s!"unknown recipe {op}"

/-- Julia's show of `V'`/`dual(V)`, or its error. -/
def showOrErr (e : Except String TensorBundle) : String :=
  match e with
  | .ok V => V.toString
  | .error _ => "<error>"

/-- A Julia field that is either a string or `{"error": …}`. -/
def jShow (j : Json) : String :=
  match j.getStr? with
  | .ok s => s
  | .error _ => "<error>"

/-- Check one space record. -/
def checkSpace (t : Tally) (r : Json) : Tally := Id.run do
  let nm := jStr r "name"
  let mut t := t
  match build (r.getObjValD "spec") with
  | .error e => return t.bad s!"{nm}: recipe failed: {e}"
  | .ok V =>
    let p := r.getObjValD "params"
    let kindOk := match jStr p "kind", V.metric with
      | "Int", .euclid | "Signature", .signature _ | "DiagonalForm", .diagonal _ => true
      | _, _ => false
    t := t.check kindOk s!"{nm}: kind {jStr p "kind"} vs {repr V.metric}"
    t := t.check (V.n == jNat p "n") s!"{nm}: n"
    t := t.check (V.options == jNat p "options") s!"{nm}: options {V.options} vs {jNat p "options"}"
    t := t.check (V.diffvars == jNat p "diffvars" && V.diffmode == jNat p "diffmode") s!"{nm}: F/D"
    t := t.check (V.name == jNat p "name") s!"{nm}: name"
    match V.metric, p.getObjValD "metric" with
    | .signature s, .num m => t := t.check (s.toNat == (jsonRat m).num.toNat) s!"{nm}: metric bits {s}"
    | _, _ => pure ()
    match p.getObjValD "diag" with
    | .arr d =>
      let js := d.map fun j => j.getStr?.toOption.getD ""
      t := t.check (V.diagValues.map showDiagEntry == js) s!"{nm}: diag {V.diagValues.map showDiagEntry}"
    | _ => pure ()
    t := t.check (V.toString == jStr r "show") s!"{nm}: show `{V.toString}` vs `{jStr r "show"}`"
    t := t.check (V.showHandle == jStr r "handle") s!"{nm}: handle `{V.showHandle}` vs `{jStr r "handle"}`"
    t := t.check (V.grade == jNat r "grade") s!"{nm}: grade"
    match r.getObjValD "isdiag" with
    | .bool b => t := t.check (V.isdiag == b) s!"{nm}: isdiag"
    | _ => pure ()
    let dm := (jArr r "diffmask").map fun | .num x => (jsonRat x).num.toNat | _ => 0
    t := t.check (#[V.diffmaskPair.1.toNat, V.diffmaskPair.2.toNat] == dm) s!"{nm}: diffmask"
    t := t.check (showOrErr V.adjoint == jShow (r.getObjValD "adjoint"))
      s!"{nm}: adjoint `{showOrErr V.adjoint}` vs `{jShow (r.getObjValD "adjoint")}`"
    t := t.check (V.dual.toString == jShow (r.getObjValD "dual"))
      s!"{nm}: dual `{V.dual.toString}` vs `{jShow (r.getObjValD "dual")}`"
    let labels := (jArr r "labels").map fun j => j.getStr?.toOption.getD ""
    t := t.check (V.labels == labels) s!"{nm}: labels {V.labels}"
    let bits := (jArr r "bits").map fun | .num x => (jsonRat x).num.toNat.toUInt64 | _ => 0
    if !bits.isEmpty then
      t := t.check (Leibniz.indexBasisAll V.n == bits) s!"{nm}: basis order"
      let blades := (jArr r "blades").map jShow
      t := t.check (bits.map (V.bladeLabel ·) == blades) s!"{nm}: blades {bits.map (V.bladeLabel ·)}"
    let subs := (jArr r "subspaces").map jShow
    for (s, b) in subs.zipIdx do
      t := t.check (V.showSub b.toUInt64 == s) s!"{nm}: subspace {b} `{V.showSub b.toUInt64}` vs `{s}`"
    match (r.getObjValD "basis_show").getStr? with
    | .ok s =>
      -- Julia's `getalgebra` cache ignores the naming scheme (quirk Q5): a
      -- scheme-2 space can get the cached scheme-1 basis of the same space
      if V.showBasis != s && V.name != 1 && ({ V with name := 1 } : TensorBundle).showBasis == s then
        t := t.defect "DirectSum Q5 getalgebra cache ignores the naming scheme"
      else t := t.check (V.showBasis == s) s!"{nm}: Λ `{V.showBasis}` vs `{s}`"
    | .error _ => pure ()
    match r.getObjValD "collect_show" with
    | .str s => t := t.check (V.showCollect == s) s!"{nm}: collect `{V.showCollect}` vs `{s}`"
    | .null => pure ()
    -- Julia raises a BoundsError for dyadic tangent subspaces (directsum.md §5.4)
    | _ => t := t.defect "DirectSum Q19 dyadic-tangent subspace display (Julia BoundsError)"
    return t

/-- String grammars: `S!`, `D!`, `V!` parsers against Julia's constructors. -/
def checkParse (t : Tally) (j : Json) : Tally := Id.run do
  let mut t := t
  for r in jArr j "signature_parse" do
    let s := jStr r "input"
    t := t.check (showOrErr (TensorBundle.parseSignature s) == jShow (r.getObjValD "show"))
      s!"S\"{s}\": `{showOrErr (TensorBundle.parseSignature s)}` vs `{jShow (r.getObjValD "show")}`"
    match TensorBundle.parseSignature s, (r.getObjValD "params").getObjValD "options" with
    | .ok V, .num m => t := t.check (V.options == (jsonRat m).num.toNat) s!"S\"{s}\": options"
    | _, _ => pure ()
  for r in jArr j "diagonal_parse" do
    let s := jStr r "input"
    t := t.check (showOrErr (TensorBundle.parseDiagonal s) == jShow (r.getObjValD "show"))
      s!"D\"{s}\": `{showOrErr (TensorBundle.parseDiagonal s)}`"
  for r in jArr j "bundle_parse" do
    let s := jStr r "input"
    t := t.check (showOrErr (TensorBundle.parseBundle s) == jShow (r.getObjValD "show"))
      s!"V\"{s}\": `{showOrErr (TensorBundle.parseBundle s)}`"
  for r in jArr j "sparse" do
    match build (r.getObjValD "spec") with
    | .ok V => t := t.check (V.showBasis == jStr r "show") s!"sparse `{V.showBasis}` vs `{jStr r "show"}`"
    | .error e => t := t.bad s!"sparse recipe: {e}"
  for r in jArr j "powers" do
    let e := jStr r "expr"
    let mine := match e with
      | "R^0" => (ℝ^1).pow 0 | "R^5" => (ℝ^1).pow 5 | "(R^2)^3" => (ℝ^2).pow 3
      | _ => ((ℝ^1)′).pow 2
    t := t.check (showOrErr mine == jShow (r.getObjValD "show")) s!"power {e}: `{showOrErr mine}`"
  return t

/-- Blade lookup by name against Julia `getproperty(Λ(V), name)`. Julia's sign
for repeated indices through `Λ(V)` and its errors on some dyadic names are
quirk Q16 (fixed here: the geometric product decides). -/
def checkLookup (t : Tally) (j : Json) : Tally := Id.run do
  let mut t := t
  for r in jArr j "lookup" do
    let s := jStr r "name"
    let .ok V := build (r.getObjValD "spec") | t := t.bad s!"lookup recipe {s}"
    let mine := V.lookup s
    let res := r.getObjValD "result"
    let repeated := match V.generatorsOf s with
      | some gs => decide (gs.eraseDups.length < gs.length)
      | none => false
    match (res.getObjVal? "error"), mine with
    | .ok _, none => t := t.ok
    | .ok _, some _ => t := t.defect "DirectSum Q16 name lookup (Julia throws on out-of-order dyadic names)"
    | .error _, none => t := t.bad s!"lookup {s}: Lean found nothing"
    | .error _, some r' =>
      let want : Terms := if (res.getObjValD "zero") == .bool true then #[]
        else #[((jNat res "bits").toUInt64, (match TensorBundle.parseRat (jStr res "coef") with
          | .ok x => x | .error _ => 0))]
      let got := r'.terms
      let shown := match r' with
        | .zero => "𝟎" | .blade b => V.bladeLabel b | .single c b => V.showTerm c b | _ => "?"
      if normTerms got == normTerms want && shown == jStr res "show" then t := t.ok
      else if repeated then t := t.defect "DirectSum Q16 name lookup (repeated-index sign through Λ(V))"
      else t := t.bad s!"lookup {s}: `{shown}` vs `{jStr res "show"}`"
  return t

/-- Nat array field. -/
def natArr (j : Json) (k : String) : Array Nat := (jArr j k).map fun | .num x => (jsonRat x).num.toNat | _ => 0

/-- Index tables `n ≤ 12` and spot checks up to `n = 22`. -/
def checkIndex (t : Tally) (j : Json) : Tally := Id.run do
  let mut t := t
  for r in jArr j "index_tables" do
    let n := jNat r "n"
    let masks := (List.range (2 ^ n)).toArray.map (·.toUInt64)
    for (row, g) in (jArr r "indexbasis").zipIdx do
      let cell : Json → UInt64 := fun | .num x => (jsonRat x).num.toNat.toUInt64 | _ => 0
      let jb : Array UInt64 := match row with
        | .arr a => a.map cell
        | _ => #[]
      t := t.check (Leibniz.indexBasis n g == jb) s!"indexbasis {n} {g}"
    t := t.check (masks.map (Leibniz.bladeIndex n) == natArr r "bladeindex") s!"bladeindex {n}"
    t := t.check (masks.map (Leibniz.basisIndex n) == natArr r "basisindex") s!"basisindex {n}"
    t := t.check (masks.map (Leibniz.spinIndex n) == natArr r "spinindex") s!"spinindex {n}"
    t := t.check (Leibniz.gdimsall n == natArr r "gdimsall") s!"gdimsall {n}"
    -- Leibniz quirk Q2: Julia's cumulative-sum cache is wrong for n < 2
    let q2 := fun (t : Tally) (ok : Bool) (msg : String) =>
      if ok then t.ok else if n < 2 then t.defect "Leibniz Q2 cumsum/antiindex cache seeding (n < 2)" else t.bad msg
    t := q2 t (masks.map (Leibniz.antiIndex n) == natArr r "antiindex") s!"antiindex {n}"
    t := q2 t (Leibniz.binomcumsum n == natArr r "binomcumsum") s!"binomcumsum {n}"
    t := q2 t (Leibniz.spincumsum n == natArr r "spincumsum") s!"spincumsum {n}"
    t := q2 t (Leibniz.anticumsum n == natArr r "anticumsum") s!"anticumsum {n}"
  for r in jArr j "index_spots" do
    let n := jNat r "n"
    let b := (jNat r "b").toUInt64
    t := t.check (Leibniz.bladeIndex n b == jNat r "bladeindex" && Leibniz.basisIndex n b == jNat r "basisindex")
      s!"spot n={n} b={b}"
  return t

/-- Glyph primitives, complement masks, grade parities, `pdep`. -/
def checkPrinting (t : Tally) (j : Json) : Tally := Id.run do
  let mut t := t
  for r in jArr j "printindex" do
    let i := jInt r "i"
    let l := (r.getObjValD "label") == .bool true
    let e := jStr r "prefix"
    t := t.check (Leibniz.printIndex i l e == jStr r "out") s!"printindex {i} {l} {e}: {Leibniz.printIndex i l e}"
  let p62 := j.getObjValD "printindices_62"
  let all : List Int := (List.range 62).map fun i => Int.ofNat (i + 1)
  t := t.check (Leibniz.printIndices all false "v" == jStr p62 "v") "printindices 62 v"
  t := t.check (Leibniz.printIndices all false "w" == jStr p62 "w") "printindices 62 w"
  t := t.check (Leibniz.printIndices all true "v" == jStr p62 "vl") "printindices 62 v label"
  for r in jArr j "complement" do
    let c := Leibniz.complement (jNat r "N") (jNat r "B").toUInt64 (jNat r "D") (jNat r "P")
    t := t.check (c.toNat == jNat r "C") s!"complement {jNat r "N"} {jNat r "B"} {jNat r "D"} {jNat r "P"}"
  let gp := j.getObjValD "grade_parities"
  let bools := fun (k : String) => (jArr gp k).map (· == .bool true)
  let gs := (List.range 65).toArray
  t := t.check (gs.map Leibniz.parityreverse == bools "reverse") "parityreverse"
  t := t.check (gs.map Leibniz.parityinvolute == bools "involute") "parityinvolute"
  t := t.check (gs.map Leibniz.parityclifford == bools "clifford") "parityclifford"
  for r in jArr j "expandbits" do
    t := t.check ((pdep (jNat r "B").toUInt64 (jNat r "S").toUInt64).toNat == jNat r "expandbits")
      s!"expandbits {jNat r "S"} {jNat r "B"}"
  return t

/-- Run the space/index/printing suite. -/
def run : IO Tally := do
  let txt ← IO.FS.readFile "Tests/DirectSum/golden/spaces.json"
  let j ← match Json.parse txt with
    | .ok j => pure j
    | .error e => throw (IO.userError s!"spaces.json: {e}")
  let mut t : Tally := {}
  for r in jArr j "spaces" do t := checkSpace t r
  t := checkParse t j
  t := checkIndex t j
  t := checkPrinting t j
  t := checkLookup t j
  return t

end DirectSumTests.Spaces
